### PR TITLE
Add support for Python 3.5

### PR DESCRIPTION
**Pull request by waylan**
Also include a fix for one failing test with HTMLParser. Three additional
tests are still failing for a different problem related to search.

If I work out that issue, I'll push up another commit to fix it here.

### CODE REVIEW

**Comment by waylan** [comment]
Oh, for got to mention this addresses #751.

**Comment by waylan** [comment]
Just pushed another commit which should resolve all issues with Python 3.5. Interestingly, all the issues revolved around HTMLParser.

**Comment by waylan** [comment]
Groan, it appears that Travis (at least, still waiting on appveyor) does not yet support Python 3.5.

**Comment by waylan** [comment]
Hmm, the [Travis build log][1] clearly states: `InterpreterNotFound: python3.5`, however the [docs][2] list 3.5 as being supported. I wonder if we need to migrate to the [new system][3]. Perhaps new Python versions are not being added to legacy?

[1]: https://travis-ci.org/mkdocs/mkdocs/jobs/91721711
[2]: http://docs.travis-ci.com/user/languages/python/#Choosing-Python-versions-to-test-against
[3]: http://docs.travis-ci.com/user/migrating-from-legacy/

**Comment by waylan** [comment]
Well Travis runs a lot fast on the new system, but still no [Python 3.5 support][1].

[1]: https://travis-ci.org/mkdocs/mkdocs/jobs/91724663

**Comment by facelessuser** [comment]
@waylan Try what I do here: https://github.com/facelessuser/pymdown-extensions/blob/master/.travis.yml

**Comment by waylan** [comment]
Thanks @facelessuser, that did the trick. Doesn't really make sense to me that that would matter unless Py35 is not yet installed on all systems. Perhaps setting the system Python to 3.5 forces the builds to run on a system which has Py35 available.

Except now Flake8 gives an [error][1] because `unicode` is not defined. That was not a problem in Python2.7.

[1]: https://travis-ci.org/mkdocs/mkdocs/jobs/91727004

**Comment by facelessuser** [comment]
You can probably try`python -m flake8 .`  but maybe use the correct python.  I think there is a way to call a specific python version in Travis...

**Comment by facelessuser** [comment]
It's kind of a pain.  I'll be happy when travis supports py35 proper.

**Comment by facelessuser** [comment]
The other alternative is to add `# noqa` to things line unicode (which should be in one place).

**Comment by waylan** [comment]
Flake8 is called from Travis through a Tox env. So I just told Tox to use Python2.7 for the Flake8 env. Finally have all tests passing on Travis.

**Comment by facelessuser** [comment]
Nice, that's a good trick to know.

**Comment by waylan** [comment]
I just noticed this line in the Travis build logs:

```
3.5 is not installed; attempting download
```

Apparently Python 3.5 is not actually installed on any of Travis' systems. However, when the config sets that version as the system version, it gets installed as part of the build dependencies. I suppose when that line no longer appears in build logs, we'll know that it is available and we will no longer need to set the system Python to 3.5.

Regardless, in my attempts to work around this, I switched to the new infrastructure and *wow* is it faster. Glad for that.

**Comment by d0ugal** [comment]
Thanks!

**Comment by waylan** [comment]
You can close #751 now that this is merged.

**Pull request merged**
