### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Justman10000**

### CODE REVIEW

**Comment by Justman10000** [comment]
@oprypin

**Comment by Justman10000** [comment]
> This can be achieved by overriding the themes, I'm not sure why we should add this. Your PR does not mention your motivations either so if I had to guess, I'd say no I'm afraid.

If you simply close PRs from your users, don't be surprised if they are suddenly gone! No pig will develop their own theme just to remove the copyright!

As already indicated, you can write your shit self! I don't support mkdocs in any way anymore!

**Comment by ultrabug** [comment]
There's no need to be insulting. Everyone's here on their free, passionate time, including you and there's no one better suited to respect that than Open Source Maintainers.

I've tried asking questions and we can't afford to let open requests/PRs stack up without context so this is normal that this PR has been closed. I would have done it myself too if I had the time.

That being said, you might find helpful to read: https://www.mkdocs.org/about/contributing/

I wish you the best in whatever other project you might end up contributing.

**Comment by Justman10000** [comment]
> There's no need to be insulting. Everyone's here on their free, passionate time, including you and there's no one better suited to respect that than Open Source Maintainers.
> 
> I've tried asking questions and we can't afford to let open requests/PRs stack up without context so this is normal that this PR has been closed. I would have done it myself too if I had the time.
> 
> That being said, you might find helpful to read: https://www.mkdocs.org/about/contributing/
> 
> I wish you the best in whatever other project you might end up contributing.

That may be all, but if you close PRs, you destroy the work of others! As I said, no pig will write an entire theme just to override the copyright!

**Comment by Justman10000** [comment]
There is also a context that you can clearly see in the commits! But I feel compelled to advise others against mkdocs and to recommend a competitor...

**Comment by Justman10000** [comment]
On the other hand, what I could also do is develop a theme for everyone, where you can also overwrite the copyright... I would then like to have this theme officially adopted here...

**Comment by pawamoy** [comment]
> That may be all, but if you close PRs, you destroy the work of others

That is why you should open an issue first, see if the change interests maintainers, and only then implement it. By opening a PR without prior discussion, and without any context or reasoning at all, you are asking other people to spend their free time to review your code and understand themselves why you made those changes. That is not respectful of their time.

Even if that's not clearly explained in the README or CONTRIBUTING files, that is generally what is expected in most open source projects, so I would always recommend proceeding like that (issue/discussion first, PR if maintainers OK) :slightly_smiling_face: 

About theming: you don't have to write a whole theme. Not sure about MkDocs built-in themes but other third-party themes allow to overwrite only small parts of the HTML templates.

**Comment by Justman10000** [comment]
However, it makes no sense! If I create an issue explaining this, who will stop someone else from stealing the idea from me?

**Comment by pawamoy** [comment]
At this point I'm not sure if you're trolling or not :confused: (my apologies if you're not). Stealing the idea? If you ask for something and someone else implements it for you, you get what you wanted, no? Or maybe authoring the pull request / commits yourself is more important to you? I can understand that, but keep in mind that contributing to open source projects is not a competition.

**Comment by trel** [comment]
You want to make sure you get credit for the idea of not giving credit to others?

**Comment by pawamoy** [comment]
@Justman10000, here are some excellent articles about open source, by Brett Canon, that you could find interesting:

- [How I stay happy making open source software](https://snarky.ca/how-i-stay-happy-making-open-source-software/) (2015)
- [Setting expectations for open source participation](https://snarky.ca/setting-expectations-for-open-source-participation/) (2018)
- [The social contract of open source](https://snarky.ca/the-social-contract-of-open-source/) (2021)

**Comment by Justman10000** [comment]
> but keep in mind that contributing to open source projects is not a competition

> You want to make sure you get credit for the idea of not giving credit to others?

<br>
Well, if a maintainer implements one of my ideas, where I'm powerless because I lack the code experience, it's certainly not a problem! However, if it's something like this PR, I can do it myself, so why would a maintainer do it? Or another contributor?

**Comment by pawamoy** [comment]
You seem to think that by discussing the feature first, someone else would jump in and implement it before you get the chance to. That's not what happen in 99.99% of the time (I actually *never* saw it happen). If you convinced maintainers that your feature is useful, they will *happily* let you have a try at implementing it, and even help you during review of your pull request. Same for other contributors happening to watch activity on the repository: nobody will jump in to "steal" your idea. Sometimes different implementations of a feature are offered by different contributors in separate PRs, and the best implementation wins ("best" here depends on the project and its standards, not just code quality or performance). But that's fine! The goal is to make the project better, not to gain tons of credits.

**Comment by Justman10000** [comment]
> You seem to think that by discussing the feature first, someone else would jump in and implement it before you get the chance to. That's not what happen in 99.99% of the time (I actually _never_ saw it happen). If you convinced maintainers that your feature is useful, they will _happily_ let you have a try at implementing it, and even help you during review of your pull request. Same for other contributors happening to watch activity on the repository: nobody will jump in to "steal" your idea. Sometimes different implementations of a feature are offered by different contributors in separate PRs, and only the best implementation is accepted ("best" here depends on the project and its standards, not just code quality or performance). And that's fine! The goal is to make the project better, not to gain tons of credits.

Well, if that's the case, that relieves me...

**Pull request closed without merging**
