### PR TITLE
Remove `.editorconfig`

### PR DESCRIPTION
**Pull request by tomchristie**
Minor cleanup.

### CODE REVIEW

**Comment by pawamoy** [comment]
What's the rationale? I thought .editorconfig was widely used by most editors.

**Comment by tomchristie** [comment]
Hmmm... I hadn't noticed it in other open source projects, tho it's certainly [more widely adopted](https://github.com/editorconfig/editorconfig/wiki/Projects-Using-EditorConfig) than I anticipated.

And this character does seem friendly...

<a href="https://editorconfig.org/">logo</a>

> What's the rationale?

It's quite easy for project directories to end up with a little bit of everyone's favorite pet project unless there's a bit of pruning applied. 🤷🏼‍♂️

**Comment by pawamoy** [comment]
> It's quite easy for project directories to end up with a little bit of everyone's favorite pet project unless there's a bit of pruning applied. 🤷🏼‍♂️ (less is more maxim)

Definitely agree with that :smile: 

With Ruff formatting in place, plus the action that auto-formats code in PRs, I suppose `.editorconfig` could be dropped :+1: No strong opinion :slightly_smiling_face:

**Comment by squidfunk** [comment]
`.editorconfig` is pretty much the industry standard. IMHO, it should not be removed, as all modern editors respect it and will automatically configure the most basic things like empty lines at files endings, usage of tabs over spaces (for Python).

**Pull request closed without merging**
