### PR TITLE
docs: add Layer0 deployment guide

### PR DESCRIPTION
**Pull request by rishi-raj-jain**

### CODE REVIEW

**Comment by oprypin** [comment]
You didn't disclose your affiliation with the product being advertised here. This is spam.

**Comment by rishi-raj-jain** [comment]
> You didn't disclose your affiliation with the product being advertised here. This is spam.

1. The contributing.md never asked me to,
2. I've never tried to hide it. It's there on my github, twitter, linkedin, and portfolio. If somebody even googled for me, they'd see my affiliation instantly in the search results,
3. It's not an advertisement/spam, because it just contains a link to the guide of the platform. Not a single word about the platform, it's just to the point.

**Comment by rishi-raj-jain** [comment]
@oprypin

**Comment by rishi-raj-jain** [comment]
> You didn't disclose your affiliation with the product being advertised here. This is spam.

1. The contributing.md never asked me to,
2. I've never tried to hide it. It's there on my github, twitter, linkedin, and portfolio. If somebody even googled for my name, they'd see my affiliation instantly in the search results,
3. It's not an advertisement/spam, because it just contains a link to the guide of the platform. Not a single word about the platform, it's just to the point.

**Pull request closed without merging**
