### PR TITLE
Add YAML placeholder tags that resolve to current paths

### LINKED ISSUE #2154: Support for relative base_path in markdown_extensions
Many extensions need to know the base path of the currently rendered Markdown file, as they are supposed to include assets relative to the markdown file. Two of them are:

- [markdown-include](https://github.com/cmacmackin/markdown-include)
- [pymdownx.snippets](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/)

Both make use of the config variable `base_path` for including other files, so in order to configure it, you would specify:

```yaml
markdown_extensions:
  - pymdownx.snippets:
      base_path: docs
  - markdown_include.include:
      base_path: docs
```

# Currently

Please take a look at this [example repository](https://github.com/dersimn/mkdocs-snippets-issue).

```
|-- README.md
|-- docs
|   |-- big_topic
|   |   |-- index.md
|   |   `-- more_important_code.c
|   |-- index.md
|   `-- smaller_topic
|       |-- hello_world.c
|       `-- index.md
`-- mkdocs.yml
```

Currently you would have to include the `*.c` files with their full path, so in both files you would have to write:

```
    --8<-- "smaller_topic/hello_world.c"
```

```
    --8<-- "big_topic/more_important_code.c"
```

# Why is this bad?

This is fine for Markdown files that are created and maintained for just one website, but we are currently including generic sub topics into our site that are shared among many repositories via `git submodule`. For e.g. some introduction topic on how to set up Docker. It's obvious that include paths must be relative to the Markdown file in this case, like:

```
    --8<-- "hello_world.c"
```

```
    --8<-- "more_important_code.c"
```

# Desirable solution

If we want to be able to specify relative paths in every Markdown file, the `base_path` variable need to change with every Markdown file to be rendered, so it can't simply be included in `mkdocs.yml`.  
This makes my feature request different from #998 #777 #761, because I'm not able to alter the `.md` files as they are shared over multiple projects.

It would be nice if we could specify something like

```yaml
markdown_extensions:
  - pymdownx.snippets:
      base_path: $relative
  - markdown_include.include:
      base_path: $relative
  - one of many other extensions that use exacly 'base_path' as variable:
      base_path: $relative
```

that would then make MkDocs add the currently valid path as `base_path` variable for each rendered Markdown file.

This is an issue for the one who _calls_ the plugin, and not the plugin itself, as an additional (dynamic) `base_path` must be exchanged [at this point in code](https://github.com/mkdocs/mkdocs/blob/ff0b7260564e65b6547fd41753ec971e4237823b/mkdocs/structure/pages.py#L173):

```python
md = markdown.Markdown(
    extensions=extensions,
    extension_configs=config['mdx_configs'] or {}
)
```

Currently (with the upper config from my example), `extension_configs` would contain something in the structure of [this](https://python-markdown.github.io/reference/#extension_configs):

```python
extension_configs = {
    'pymdownx.snippets': {
        'base_path': '$relative'
    },
    'markdown_include.include': {
        'base_path': '$relative'
    }
}
```

We need to replace `$relative` here with the proper path depending on the current navigation.

[1]: https://facelessuser.github.io/pymdown-extensions/faq/#github-ish-configurations

### PR DESCRIPTION
**Pull request by oprypin**
* Closes #2154

```yaml
- !relative  # Obtains the directory of the currently rendered Markdown file
- !relative $config_dir  # Obtains the directory of mkdocs.yml
- !relative $docs_dir  # Obtains the docs_dir
- !relative $docs_dir/some/child/dir
```

### CODE REVIEW

**Comment by oprypin** [comment]
Tagging @facelessuser now also on the pull request for any comments. Now I actually mention `pymdownx.snippets` directly in docs.

**Comment by squidfunk** [comment]
Could we allow plugins to register custom YAML tags? I suspect that this would need to be implemented outside of the plugin, because when the plugin is loaded, the configuration has already been parsed, but maybe plugins could provide something like a `loader.py` file that MkDocs checks and executes before parsing the configuration 😊

**Comment by oprypin** [comment]
There's no clear technical solution how to do that (see also https://github.com/mkdocs/mkdocs/discussions/3261), no known use case, and so no plan to do that

**Comment by squidfunk** [comment]
It would be very helpful for the new [projects](https://squidfunk.github.io/mkdocs-material/setup/building-an-optimized-site/#built-in-projects-plugin) plugin in Material for MkDocs to define tags to inline navigation from projects into the top-level site and other custom tags for additional features. From the top of my head: If a project defines an `__init__.py` or `loaders.py` next to `mkdocs.yml`, include that before attempting to parse the configuration.

That'll work, wouldn't it?

**Comment by oprypin** [comment]
That sounds like not something that would require tags to function. Instead of `- !foo bar` you could just define `- foo: bar` or something. Feel free to open a discussion if you want to figure out a way to achieve something in the configs.

**Comment by squidfunk** [comment]
Thanks, I'll think a little about this and might open a dedicated discussion.

**Pull request merged**
