### PR TITLE
Ensure all errors and warnings are logged before exiting.

### LINKED ISSUE #536: Improve error/warning handling in Config
While working on moving the markdown extension handling to the config, I noticed a few oddities with how errors and warnings are handled within the config. And taking a closer look at the code I see even more. I could just do a PR, but wanted some feedback on where you want to take this.

1.  I noticed that you need to hardcode the config key into any warnings (see this [example][1]) . This is bad as the same ConfigOption class could be used for more than one key (for example, if the Type or URL types raised a warning). `base.Config._validate` does the right thing with errors and uses the current key (see [L51][2]). The same thing should happen for errors two lines above.

2. Why don't warnings actually use warnings? Why not follow the pattern used for errors and define a `ValidationWarning` which subclasses [`warnings.Warning`][3]. Then within the code call `raise ValidationWarning('some message...')` and in `base.Config._validate` add a catch for warnings in addition to the current catch for errors. Using the same API for both warnings and errors seems more sensible to me (and easier to remember).

3. Why are the errors being obscured? Only the message from the error is saved (see [L51][2]) and then later a new error is raised (see [L148][4]). Wouldn't it be better if the errors themselves were saved and re-raised? It would certainly help with debugging. Yes, I realize that if multiple errors were raised, only one could get re-raised. Not sure what the best solution is here for errors. Maybe log all the errors and then raise the first one? At least that way the user can work through them one at a time if the traceback is needed to figure out what went wrong.

[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/config/config_options.py#L224
[2]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/config/base.py#L51
[3]: https://docs.python.org/2/library/exceptions.html#exceptions.Warning
[4]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/config/base.py#L148

### PR DESCRIPTION
**Pull request by waylan**
Also ensure all debug messages are logged. And exit without
creating a new, unhelpful traceback by raising SystemExit.
Note that `sys.exit` raises SystemExit. However, by raising it
explicitly, we can also output a helpful explaination of why
the program exited. The program exists with an exit code of 1
to indicate is failed.

Fixes #536.

### CODE REVIEW

**Comment by d0ugal** [comment]
Awesome, this looks great. FYI, I'm holding off on new features to make rolling a 0.13.2 easier if I need to do it for #554 but I consider this a bug fix, so I'll include it if I make another point release.

Just waiting for CI, then I'll happily merge. Thanks again!

**Comment by d0ugal** [comment]
Looks like it needs a small test update to take into account the string -> exception change.

**Comment by waylan** [comment]
I've fixed the failures and moved the "clean exit on error" handling to the CLI as it should only ever be needed there.

**Comment by d0ugal** [comment]
Thanks!

**Pull request merged**
