### PR TITLE
Allow adding event handlers at multiple priorities

### PR DESCRIPTION
**Pull request by oprypin**
-within one plugin.

### CODE REVIEW

**Comment by squidfunk** [comment]
Why do you think this should be supported?

**Comment by oprypin** [comment]
I think a better question is why shouldn't it be supported. Right now it's a limitation based only on how it's implemented. If someone was designing this system anew, surely they wouldn't say that it's *better* that you can't have an early on_files handler if you already have a late handler for it.

**Comment by squidfunk** [comment]
Okay, so I read that there's no immediate need why this get's implemented, but it's a nice-to-have. From a plugin author's perspective, I'm not sure it's necessary, though. At least, I haven't seen one sound use case that would mandate for it.

**Review by ultrabug — APPROVED** [review]
I love the idea and can clearly see use cases, thanks!

**Pull request merged**
