### PR TITLE
Pages Refactor

### PR DESCRIPTION
**Pull request by waylan**
Probably still needs some tweaks, but I believe this is fully functional. I wanted to get this in front of others for review, especially third party theme authors (@squidfunk, @notpushkin, @chrissimpkins, @hfagerlund, @cjsheets, @michaeltlombardi).

Some of the backward incompatible changes do not have a graceful upgrade path, but the underlying structure is so drastic that its really any way to support both the old and new. As this is intended to be included in the 1.0 release, there is no requirement to maintain compatibility (we are making a major release) and we need to get this correct now as we will be stuck with it throughout the 1.x release cycle.

The documentation changes and release notes provide a decent summary of the changes made. I've copied the release notes below. Some additional information, including notes regarding some of the decisions made are included in the commit message for the second commit. The first commit is from @tomchristie's work in #689, which this builds off of.

> #### Internal Refactor of Pages, Files, and Navigation
> 
> Internal handling of pages, files and navigation has been completely refactored.
> The changes included in the refactor are summarized below.
> 
> * Support for hidden pages. All Markdown pages are now included in the build
>   regardless of whether they are included in the navigation configuration
>   (#699).
> * The navigation can now include links to external sites (#989 & #1373).
> * Page data (including titles) is properly determined for all pages before any
>   page is rendered (#1382).
> * Automatically populated navigation now sorts index pages to the top. In other
>   words, The index page will be listed as the first child of a directory, while
>   all other documents are sorted alphanumerically by file name after the index page (#1042).
> * A `README.md` file is now treated as an index file within a directory and
>   will be rendered to `index.html` (#608).
> * An [on_files] plugin event has been added, which could be used to include
>   files not in the `docs_dir`, exclude files, redefine page URLs (i.e.
>   implement extensionless URLs), or to manipulate files in various other ways.
> 
> ##### Backward Incompatible Changes
> 
> As part of the internal refactor, a number of backward incompatible changes have
> been introduced, which are summarized below.
> 
> ###### URLS have changed when `use_directory_urls` is `False`
> 
> Previously, all Markdown pages would be have their filenames altered to be index
> pages regardless of how the [use_directory_urls] setting was configured.
> However, the path munging is only needed when `use_directory_urls` is set to
> `True` (the default). The path mungling no longer happens when
> `use_directory_urls` is set to `False`, which will result in different URLs for
> all pages that were not already index files. As this behavior only effects a
> non-default configuration, and the most common user-case for setting the option
> to `False` is for local file system (`file://`) browsing, its not likely to
> effect most users. However, if you have `use_directory_urls` set to `False`
> for a MkDocs site hosted on a web server, most of your URLs will now be broken.
> As you can see below, the new URLs are much more sensible.
> 
> | Markdown file   | Old URL              | New URL        |
> | --------------- | -------------------- | -------------- |
> | `index.md`      | `index.html`         | `index.html`   |
> | `foo.md`        | `foo/index.html`     | `foo.html`     |
> | `foo/bar.md`    | `foo/bar/index.html` | `foo/bar.html` |
> 
> Note that there has been no change to URLs or file paths when
> `use_directory_urls` is set to `True` (the default), except that MkDocs more
> consistently includes an ending slash on all internally generated URLs.
> 
> ###### The `pages` configuration setting has been renamed to `nav`
> 
> The `pages` configuration setting is deprecated and will issue a warning if set
> in the configuration file. The setting has been renamed `nav`. To update your
> configuration, simply rename the setting to `nav`. In other words, if your
> configuration looked like this:
> 
> ```yaml
> pages:
>     - Home: index.md
>     - User Guide: user-guide.md
> ```
> 
> Simply edit the configuration as follows:
> 
> ```yaml
> nav:
>     - Home: index.md
>     - User Guide: user-guide.md
> ```
> 
> In the current release, any configuration which includes a `pages` setting, but
> no `nav` setting, the `pages` configuration will be copied to `nav` and a
> warning will be issued. However, in a future release, that may no longer happen.
> If both `pages` and `nav` are defined, the `pages` setting will be ignored.
> 
> ###### Template variables and `base_url`
> 
> In previous versions of MkDocs some URLs expected the [base_url] template
> variable to be prepended to the URL and others did not. That inconsistency has
> been removed. All  URLs must now be joined with the `base_url`. As previously, a
> slash must be included between the `base_url` and the URL variable. For example,
> a theme template might have previously included a link to the `site_name` as:
> 
> ```django
> <a href="{{ nav.homepage.url }}">{{ config.site_name }}</a>
> ```
> 
> And MkDocs would magically return a URL for the homepage which was relative to
> the current page. That "magic" has been removed and the `base_url` must now be
> explicitly included:
> 
> ```django
> <a href="{{ base_url }}/{{ nav.homepage.url }}">{{ config.site_name }}</a>
> ```
> 
> This change applies to any navigation items and pages, as well as the
> `page.next_page` and `page.previous_page` attributes. For the time being, the
> `extra_javascript` and `extra_css` variables continue to work as previously
> (without `base_url`), but they have been deprecated and the corresponding
> configuration values (`config.extra_javascript` and `config.extra_css`
> respectively) should be used with `base_url` instead.
> 
> Any URL variables which should not be used with `base_url` are explicitly
> documented as such.

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Thanks for the summary and poke.  Much appreciated! I will have a look at this over the weekend.  What is time frame for 1.0 rollout?

**Comment by squidfunk** [comment]
Sounds great and looks good to me!

**Comment by waylan** [comment]
The time frame for 1.0 is "when it's done." This PR should resolve about half of the open issues on the 1.0 milestone. Most everything else is just housekeeping type stuff, so I expect by the end of summer. That said, this is being worked in in my spare time so no guarantees.

**Comment by chrissimpkins** [comment]
Wasn't a criticism, rather it was to place changes on our end on my TODO list radar in a timely fashion.  Sounds good to me.  The more time you need the better from my standpoint :)

**Comment by tomchristie** [comment]
Holy smokes

**Comment by waylan** [comment]
We're getting a [test failure][1] in the "integration tests" which do a "strict" build of the MkDocs documentation (the same issue is causing the linkchecker test to fail) . Of course, a "strict" build errors if any warnings are issued. And a build of the MkDocs documentation currently includes the following warning:

```
WARNING -  Documentation file 'index.md' contains a link to 'img\favicon.ico' 
which does not exist in the documentation directory.
```

That error is correct. However, the image does exist in the generated site as it comes from the theme. #872 requests the ability to validate image links in documentation pages and this refactor makes that very easy to implement (it appears that I missed listing that feature and issue in the release notes). The tricky part is when the link points to an internal file which comes from an external source (external links are ignored in this check). Should we include the non-template theme files in the check? A [comment][2] I inserted in the code seems to indicate I had intended to do something about this at one point. Perhaps we should even include non-template theme files in the `Files` collection? The problem is that the `Files` collection assumes there is only ever one file for any output location. However, it is documented and understood that theme files get written first, then files from the `docs_dir` can overwrite a file of the same name.

I was thinking I could deal with this later, but didn't consider that it would cause the Integration tests to fail.

[1]: https://travis-ci.org/mkdocs/mkdocs/jobs/389848158#L546
[2]: https://github.com/mkdocs/mkdocs/pull/1504/commits/ac6581b8ef338e301f65c72ecd720863cfd5cacf#diff-30fed26d76866f92435a3b102e91c182R219

**Comment by charlesreid1** [comment]
Re #1504 and this change:

> A README.md file is now treated as an index file within a directory and
will be rendered to index.html (#608).

does this implement the behavior you described in [this comment](https://github.com/mkdocs/mkdocs/issues/608#issuecomment-328311230)?

> when no index.md is found within a dir within the docs_dir, but README.md is found, then README.md is used and treated as if it was index.md

**Comment by waylan** [comment]
> is the index.md name being done away with entirely in favor of using README.md?

No. I never said that and why would we do that. README.md is an optional alternate index file for those people who want it.

**Comment by hfagerlund** [comment]
Thanks @waylan. Looking forward to trying this out.

**Comment by waylan** [comment]
While working on this, I discovered a weird error which I reported in #1516. As the error also exists in master, it appears to not be related to this work, so I'll address that separately.

**Comment by waylan** [comment]
FYI to those following this, **especially theme authors**, the above described behavior for URLs and the use of `base_url` is being changed slightly due to an oversight on my part. See #1526 for details.

**Comment by timani** [comment]
Thanks for all the updates @waylan, these are all awesome and welcome changes. Is there a way to test a dev build or an ETA of when this will be available as a stable release?

**Comment by waylan** [comment]
@timani this will be included in the next release (1.0) when the [1.0 Milestone][1] is complete (we are almost there). In the meantime, you can always install the latest in the master branch directly from GitHub:

```
pip install https://github.com/mkdocs/mkdocs/archive/master.zip
```

[1]: https://github.com/mkdocs/mkdocs/milestone/4

**Comment by timani** [comment]
great! I'll subscribe to the [1.0 Milestone](https://github.com/mkdocs/mkdocs/milestone/4) 

I also see [1.0 Beta](https://pypi.org/project/mkdocs/1.0b1/) is already out so that should do the trick
 
```
pip install mkdocs==1.0b1
```

thanks @waylan

**Pull request merged**
