### PR TITLE
Re-generate localization files

### PR DESCRIPTION
**Pull request by oprypin**

### CODE REVIEW

**Comment by tomchristie** [comment]
Do we currently have this process documented anywhere?

**Comment by ultrabug** [comment]
Should be in here: https://www.mkdocs.org/dev-guide/translations/

**Review by tomchristie — COMMENTED** [review]
I can't see any content changes here.
Should we just pass on this?

**Comment by pawamoy** [comment]
> I can't see any content changes here.

Line numbers were updated to match the location in HTML sources.

**Comment by oprypin** [comment]
Could someone unblock this pull request please.....

**Review by tomchristie — APPROVED** [review]

**Pull request merged**
