### PR TITLE
Some advance with setup_command

### PR DESCRIPTION
**Pull request by williamjmorenor**
Signed-off-by: William Moreno Reyes <williamjmorenor@gmail.com>

### CODE REVIEW

**Comment by williamjmorenor** [comment]
Hi I have been doing some testing with the setup_command (https://github.com/mkdocs/mkdocs/issues/918).

The comand seems to work, I can run:

>>> setup_command.BuildDoc.run()

The build_mkdocs is visible with python setup.py --help-commands

But when I run the command I got:

python3 setup.py build_mkdocs 
running build_mkdocs
Usage: setup.py [OPTIONS]

Error: Got unexpected extra argument (build_mkdocs)

I am doing something wrong with the run() module but I can not find what is.

**Comment by waylan** [comment]
I'm just guessing here, but you are using the Click `build` command (from `__main__.py`). Click gets its arguments from reading argv and argv contains the argument `build_mkdocs` which is unknown to Click.  In my experience,  nesting one cli system inside another will almost always break without some extra steps. I would suggest searching for how to use Click with disutils commands.

**Comment by waylan** [comment]
Actually, if you look at the Spinx example you pointed to in #918, you will see that they re-implement all of the options directly using disutils command tools. It may be that that is the only way it will work.

**Comment by d0ugal** [comment]
I played around with this and tried to make it work. The issue you are hitting is the conflict between different command line frameworks. Click looks at the full input path `python setup.py build_mkdocs` command and spots `build_mkdocs` as an argument, but that isn't one that we have registered in the Click build command.

I think @waylan is correct, the easiest way would be to just allow build be called with no optional arguments. So, just like calling `mkdocs build` but don't support `mkdocs build --theme...` etc. I think that would be the best option.

Otherwise you would need to duplicate all the command line options and we would need to maintain them both. I don't want to do that.

**Comment by waylan** [comment]
Click has the [CLIRunner][1] Class, for [testing][2] your commands. It allows you to pragmatically call a command, passing in options and args isolated from the current process's `argv`. Perhaps the `setup_command` could gather the options and args and pass them on to Click this way (perhaps the `--help` flag could even be passed through?). The trick would be getting `setup_command` to accept any arbitrary options and args without them being redefined. If that's possible, this should be an easy fix. If not, then I wonder if there is even any value in bothering to implement a basic, option-less, command.

[1]: http://click.pocoo.org/5/api/#click.testing.CliRunner
[2]: http://click.pocoo.org/5/testing/#basic-testing

**Comment by waylan** [comment]
I'm closing this as we don't need both the issue and PR open. Someone can always open a new PR.

**Pull request closed without merging**
