### PR TITLE
Automatically refresh the browser on edits

### LINKED ISSUE #163: Automatically refresh documentation when using `mkdocs serve`
This would make the eediting experience really neat. @ericholscher had an idea for a GUI app that could do this, but this approach might be enough.

One possible approach - inject some JavaScript that either polls or uses web sockets to be notified of an update.

### PR DESCRIPTION
**Pull request by d0ugal**
Use python-livereload to automatically refresh your browser.

Closes #163

### CODE REVIEW

**Comment by robinandeer** [comment]
I've tested this branch in Vagrant (Ubuntu Precise) and everything works as expected: edits made locally are synced to the virtual machine (where mkdocs is running) which triggers an automatic browser reload.

The only issue I noticed with the simplest setup is that you can only port forward the same port e.g. ``4000:4000`` and not ``4000:4001``. I guess that would require a proxy setting somewhere but I don't think it's a big issue.

Very nice improvement :+1:

**Comment by d0ugal** [comment]
@robinandeer Thanks!

Unfortunately, when I tested this in Windows I had a strange issue that I need to take upstream and see if they can help before I can land this.

**Comment by rickpeters** [comment]
Just today I tried using mkdocs on docker and found out that the refresh didn't work (so no live reloading). After searching all through the web I found this issue. **I can confirm that it is very essential that you use exactly the same port within the container for docker serve as you use on the host side. So when I use port 8000 within and outside the container it works great!** Maybe this can be mentioned in documentation somewhere? I am using boot2docker (1.5) on osx (yosemite) and a docker image based on official python image.

**Comment by d0ugal** [comment]
@rickpeters Thanks - sounds like it would be a good addition to the documentation.

**Pull request merged**
