### PR TITLE
Fix prev/next keyboard navigation

### LINKED ISSUE #3728: Default theme: N and P keys no longer work
Using mkdocs 1.6.0, the default theme is much better than the one in 1.5.x. It has dark mode, awesome!

If you press ? it displays a few keyboard shortcuts.

But if you press the N key to go to the next page, or the P key to go to the previous page, nothing happens, and you get this error in the console:

Uncaught DOMException: Document.querySelector: '.navbar a[rel="next"]:first' is not a valid selector
    <anonymous> http://127.0.0.1:8000/js/base.js:60

### PR DESCRIPTION
**Pull request by squidfunk**
Supersedes #3729 to fix #3728. I accidentally closed the PR by deleting my fork when cleaning up my repositories.

### CODE REVIEW

**Review by tomchristie — APPROVED** [review]

**Comment by tomchristie** [comment]
@squidfunk Do you want merge permissions to help squish some of these existing PRs?

**Comment by squidfunk** [comment]
Thanks, but I'll leave the merge to you, as I don't know when you want to release the fixes 🤟 Let me know if you need anything else. Feel free to tag me in problems related to the jQuery removal in 1.6 – I'll provide fixes asap.

**Comment by squidfunk** [comment]
@tomchristie friendly ping. Do you have an ETA for when the latest changes + approved PRs will be released?

I think the community desperately awaits the 1.6.1 release that includes this and other bugfixes. The current default MkDocs theme has several bugs due to the jQuery removal that I fixed immediately as they were reported, but my contributions are still unreleased and almost all users that use the default `mkdocs` theme are impacted. I know you're working on MkDocs 2.0, but it would be great to see the community's work not go to waste until 2.0 is ready for prime time.

**Comment by tomchristie** [comment]
No worries yep. I'll have availability to ensure a release next week. @mkdocs/core could y'all bump any tickets that need inclusion?

**Comment by squidfunk** [comment]
- #3774
- #3784

**Comment by pawamoy** [comment]
- Easy to review and merge: https://github.com/mkdocs/mkdocs/pull/3785
- Could also probably be merged and released: https://github.com/mkdocs/mkdocs/pull/3795
- https://github.com/mkdocs/mkdocs/pull/3804
- I'll see if I can send a PR for https://github.com/mkdocs/mkdocs/issues/3796

**Comment by pawamoy** [comment]
Another quick docs PR: https://github.com/mkdocs/mkdocs/pull/3808.

**Pull request merged**
