### PR TITLE
Fix an <a> tag with a /> in the readthedocs theme.

### PR DESCRIPTION
**Pull request by zarvox**

### CODE REVIEW

**Comment by d0ugal** [comment]
Good spot! Thanks!

**Comment by paulproteus** [comment]
Hi y'all! If you do a mkdocs release, then I will use this change on docs.sandstorm.io. Thanks already to @zarvox and @d0ugal for fixing & merging it!

Cheers, Asheesh.

**Comment by d0ugal** [comment]
See #796 if you want to help make a release happen.

**Comment by paulproteus** [comment]
Thanks! You've been very helpful over the past few months and I appreciate
the candor and optimism of #796. I will see what I can do.

**Pull request merged**
