### PR TITLE
Fixes #316 - titles

### LINKED ISSUE #316: If no title is provided in the mkdocs.yml use the title in the markdown file
As per the title, this came up in #308 but it's something I've wanted for a while.

### PR DESCRIPTION
**Pull request by ugocupcic**
History is squashed.

### CODE REVIEW

**Comment by ugocupcic** [comment]
I had a few commits on my master so they still appear. Hopefully it's fine with you. Let me know otherwise.

**Comment by d0ugal** [comment]
Thanks for following this up and pushing it forward!

**Comment by d0ugal** [comment]
Hmm, turned out I should have looked more closely. This doesn't work at all. The `file_to_title` function is only passed the filename, but the code in this PR expects the full path so it can open the file.

**Comment by ugocupcic** [comment]
@d0ugal any idea how to get the full path to be able to parse the file?

**Comment by d0ugal** [comment]
@ugocupcic It is surprisingly complicated :( I had a quick look, about 6 methods need to be updated to pass it down the chain and that starts to get really nasty.

I'll give it some thought, but I think we might need to find a new approach. Sorry, it turned out to be somewhat harder than I first estimated.

**Comment by ugocupcic** [comment]
Might be easier to be able to parse that `mkdocs.yml` even if we have the documentation at the root of the repository instead of in this separate docs folder?

**Pull request merged**
