### PR TITLE
Fix #834 with `code` word-wrap

### LINKED ISSUE #834: Markdown tables expand beyond window with no scrollbar
I created the following test table in a `.md` file:

```
|Test1|Test2|
|-------------|-------------|
|Hello|`really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really long code`|
```

And when loaded via a ReadTheDocs theme the resulting table looks like this:

screen shot 2016-02-21 at 6 39 10 pm

The contents of a row that expand beyond the current window are not viewable. There is also no way to scroll horizontally on the table to view the contents at the end of the row. I am assuming this is happening because the text with the `<code>` tag is not splittable.

* My `mkdocs.yml` file contains:

```
theme: readthedocs

pages:
    - Home: index.md

markdown_extensions:
  - toc:
      permalink: True
  - tables
```

* Viewing the docs using Chrome. 

Any ideas how to get around this?

### PR DESCRIPTION
**Pull request by styfle**
This fixes Issue #834 and is alternative to PR #1027.

image

/cc @waylan

### CODE REVIEW

**Comment by waylan** [comment]
I don't think this is correct. We want

```
word-wrap: break-word;
white-space: pre-wrap;
```
for code spans (as I used in #1027). This is also what the `mkdocs` theme already uses for code spans.

If you don't do this, you will find many situations were inline code will be wrapped in places you do not want it to be (consider punctuation characters used in code, etc).

**Comment by waylan** [comment]
To demonstrate, given the following HTML:

```html
<html>
<head>
<style>

p {
    width: 25em;
    border: 1px red solid;
}

.default code {
    white-space: pre;
}

.normal code {
    white-space: normal;
}

.prewrap code {
    word-wrap: break-word;
    white-space: pre-wrap;
}

</style>
<body>

<p class=default><code>a_very_long_variable_name=some_very_long_namepsace.with_a_very_long_function_name(and_a_very_long_keyword="some very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very long value")</code></p>

<p class=normal><code>a_very_long_variable_name=some_very_long_namepsace.with_a_very_long_function_name(and_a_very_long_keyword="some very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very long value")</code></p>

<p class=prewrap><code>a_very_long_variable_name=some_very_long_namepsace.with_a_very_long_function_name(and_a_very_long_keyword="some very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very long value")</code></p>

</body>
</html>
```

We get the following rendering:

screencapture

Clearly the third example is the one we want. Your example uses a long string of space separated words. As can be seen in my example, that part wraps fine in both your solution and mine, and therefore makes for a poor test. The real test is when we have code without spaces (which is more common in the real world). In fact, the example pointed to in [this comment][1] on #834 consists of a bunch of long strings without spaces.

As an aside, I realize I wrapped the code in a `p` tag rather than a `table` in my example, but I wanted the most basic minimum possible. I added the red border to each paragraph to demonstrate when the code span is staying within the confines of its parent and when it is not.

[1]: https://github.com/mkdocs/mkdocs/issues/834#issuecomment-187518884

**Comment by waylan** [comment]
Btw, one thing I do like about this fix is that the inline style is applied to all `code`  tags except for `pre code`. In the `mkdocs` theme, the inline style only applies to `code` tags inside `p` elements, which means it doesn't get applied inside list items, table cells, and various other non-p elements.

**Comment by styfle** [comment]
Do you have an example input using markdown syntax that breaks using my change?

**Comment by waylan** [comment]
With your fix, this table:

```markdown
|Test1|Test2|
|-------------|-------------|
|Hello|`a_very_very_very_long_variable_name=some_very_very_very_long_namepsace.with_a_very_very_very_long_function_name(and_a_very_very_very_long_keyword="some very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very long value")`|
```

Renders as:

screenshot

Which is clearly still not correct.

**Comment by waylan** [comment]
I have a working solution, but its king of hacky.

For code tags I have:

```css
code {
    white-space: pre-wrap;
    word-wrap: break-word;
    padding: 2px 5px;
}

pre code {
  white-space: pre;
  word-wrap: normal;
  display: block;
  padding: 12px;
  font-size: 12px;
}
```

And for the table I have:

table {
    table-layout: fixed;
}

td {
    overflow: hidden;
    max-width: 43.5em;
}
```

Which renders like this:

![screencapture](https://cloud.githubusercontent.com/assets/78846/17982408/aef8ca42-6ad5-11e6-8f42-5926beee80e3.png)

 And a narrow table was included to show we don't get any weirdness there. 

I also included a paragraph with a long code span in there to demonstrate that that works also. Weirdly, the code span in the paragraph works fine in multiple different configurations. The table is extra stubborn though. 

Without the `max-width: 43.5em` (which appears to be the maximum width the page content gets) on the `td` tag, the code does not get wrapped, no matter what styles we set on the `code` element.  The problem is, if the browser window is narrowed, that fails to shrink with the page and the problem of the code running long remains. I tried using percentages, but that seemed to have no effect. So, its a rather hacky solution.

**Comment by waylan** [comment]
Given the finickiness of the above, my inclination is to go with this for the table:

```css
table {
    width: 100%;
    overflow: auto;
    display: block;
}
```

Which just adds a scrollbar if the table is too wide. The problem then is the narrow tables:

scroll

If we could get rid of that weirdness with the border, everything would be fine (By the way, the table border is a non-problem in the `mkdocs` theme as it has no border).

I tried this:

```css
table.docutils {
    width: 100%;
    overflow: auto;
    display: block;
    border: none;
}

thead, tbody {
    border: 1px solid #e1e4e5;
}
```

Which almost works:

border

The problem there is the right side of the scrolled table is missing a border unless you scroll all the way to the right, but then its missing the left border. We need the border set on the table element.

**Comment by waylan** [comment]
My test page is in this [gist][1]. I noticed that GitHub also has a missing right border on scrolled tables (and missing left border when scrolled), so I'm okay with it too.

I'm closing this in favor of #1037.

[1]: https://gist.github.com/waylan/f5503feb9177ffc3aa790561d8220598

**Comment by styfle** [comment]
@waylan Very well documented, thanks.
I think following GitHub's rendering is a good choice.

**Comment by lcherone** [comment]
`display: block;` breaks/prevents 100% width so width is kinda useless in both githubs and this templates tables..

**Pull request closed without merging**
