### PR TITLE
Re-format code with `black -l100` and enforce it

### PR DESCRIPTION
**Pull request by oprypin**
- Remove spaces at the ends of docstrings, normalize quotes
- Some manual changes ahead of formatting code with Black
- Format code with `black -l100 --skip-string-normalization`
- Enforce Black formatter

Closes #2398 by @ultrabug

### CODE REVIEW

**Comment by oprypin** [comment]
Note: please review this commit-by-commit

* https://github.com/oprypin/mkdocs/commit/black~3
* https://github.com/oprypin/mkdocs/commit/black~2?w=1
* https://github.com/oprypin/mkdocs/commit/black~?w=1
* https://github.com/oprypin/mkdocs/commit/black

**Review by ultrabug — COMMENTED** [review]
Could you provide your rationale for sticking with py36 and skipping string normalization for reference please?

It sure does make the diffs smaller.

**Comment by oprypin** [comment]
py36 is what we have so I choose that. That can be dropped separately. Anyway it probably makes no change on the behavior.

String normalization isn't such a big win. And it was a huge sticking point in the previous discussion.
And indeed it would be a huge diff and a lot of noise if combined with this PR. We can always follow up on that part separately.

**Comment by oprypin** [comment]
I have personally looked at the whole diff at least twice and it seems good to me.

I plan to merge this today.

**Comment by oprypin** [comment]
-or raise your concerns and then I won't merge :)

**Review by ultrabug — APPROVED** [review]
I'm fine, nothing struck me and tests are OK

**Pull request merged**
