### PR TITLE
Fixes a bug when 'edit_url' is not defined in the config

### PR DESCRIPTION
**Pull request by funkyfuture**
i encountered this tailed traceback:

```
  File "/home/user/mkdocs/mkdocs/nav.py", line 180, in __init__
    self._set_edit_url(config['repo_url'], config['edit_uri'])
  File "/home/user/mkdocs/mkdocs/nav.py", line 263, in _set_edit_url
    if not edit_uri.startswith('?') and not edit_uri.startswith('#'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

### CODE REVIEW

**Comment by waylan** [comment]
Thanks for this. However, this needs a test that fails before the change and passes after before it will be accepted.

**Comment by funkyfuture** [comment]
done. i realised the bug is only evoked when `repo_name` is not a default value.

**Comment by funkyfuture** [comment]
locally i rebased, so the fix is HEAD, but it appears different here.

**Comment by waylan** [comment]
The tests for this are [here][1]. I was expecting something similar, not an integration test.

[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/tests/nav_tests.py#L614-L758

**Comment by funkyfuture** [comment]
well, i looked into this. but i couldn't evoke the bug with this test:

```python
        repo_name = 'example'
        repo_url = 'http://example.com/'
        edit_uri = None

        site_navigation = nav.SiteNavigation({
            'pages': pages,
            'repo_name': repo_name,
            'repo_url': repo_url,
            'edit_uri': edit_uri,
            'docs_dir': 'docs',
            'site_dir': 'site',
            'site_url': '',
            'use_directory_urls': True
        })
```

am i missing something?

**Comment by waylan** [comment]
Don't you want to test the case where `repo_url = None` (rather than `edit_uri`)?

**Comment by waylan** [comment]
FYI, I just pushed a fix for the missing interpreters on Travis (see #1274 & #1275). If you rebase this, the tests should all run properly now.

**Comment by funkyfuture** [comment]
> Don't you want to test the case where repo_url = None (rather than edit_uri)?

no, i'd rather test the scenario that evoked the bug, as demonstrated in the integration test. can you give me a hint how to write a test to hit that code path with a simple unit test? i'm not very deep into the code.

**Comment by waylan** [comment]
Oh right. Sorry. Are you sure you rolled back your changes before trying your test? By my reading of the code, that should be correct.

Actually, I wonder if the appropriate fix would be to address this in config validation. Validation is already ensuring the `edit_uri` setting is a string (see [mkdocs/config/defaults.py#L82][1]) However, there is no default defined. Perhaps we should add `default=''` to avoid `None` as the default?

[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/config/defaults.py#L78-L82

**Comment by funkyfuture** [comment]
> Are you sure you rolled back your changes before trying your test?

yep.

> I wonder if the appropriate fix would be to address this in config validation.

I had that thought while looking for a simple test. imo, the `edit_url` could be expanded in the config as well.

**Comment by waylan** [comment]
> the `edit_url` could be expanded in the config as well.

You make a good point. While the `edit_url` is intentionally page specific (a separate URL for each page), combining the `repo_url` and `edit_uri` from the settings only needs to happen once. Perhaps that should happen in post-validation.

Truth be told, I haven't given much attention to this feature as I expect it will get ripped out and replaced with a (more flexible) plugin anyway (the plugin API is currently available in 1.0.dev). The recent changes in this space have all been from random one-time contributors. That said, we do have a bug, which should be fixed (by the way, this PR should probably be against the master branch).

**Comment by funkyfuture** [comment]
okay, i moved the logic to the config. i see that the feature has its flaws and really should be moved to a plugin. well, it works for now.

**Comment by waylan** [comment]
@funkyfuture Thanks for the work on this. Greatly appreciated.

**Comment by funkyfuture** [comment]
@waylan shall i prepare a pr that merges this into the `1.0.dev` branch? i'd like to use this one with my use-case.

**Comment by waylan** [comment]
I expect that part of the code will go through a major rewrite for 1.0, so I wasn't all that concerned about it.

**Comment by funkyfuture** [comment]
i could throw out that stuff, but w/o a substituting plugin. would you accept that?

**Pull request merged**
