### PR TITLE
Release notes for 1.6.0

### PR DESCRIPTION
**Pull request by oprypin**
Preview: https://oprypin.github.io/mkdocs/about/release-notes/#version-160-2024-04-18

I still plan to do another stylistic pass over this, but for now these release notes are ready for anyone who wants to check these changes **prior** to the release.

PRs still remaining to be merged: https://github.com/mkdocs/mkdocs/milestone/18

### CODE REVIEW

**Comment by pawamoy** [comment]
Thanks @oprypin, both the release notes and the upgraded `mkdocs` theme look good :+1:

**Comment by Andre601** [comment]
I have to say, the dark mkdocs theme looks great. Really well done.

**Review by pawamoy — APPROVED** [review]

**Comment by tomchristie** [comment]
Thanks @oprypin.

Related to this PR... what's the current deploy process for mkdocs releases?

**Comment by oprypin** [comment]
1. Merge a PR that changes the version in `__init__.py` (this)
2. Create and push a tag
3. (GitHub Actions automatically pushes to PyPI)
4. `mkdocs gh-deploy`
5. Publish a "release" on GitHub, with copied release notes but they need to be manually edited so that links go to mkdocs.org

**Comment by oprypin** [comment]
5. `mkdocs gh-deploy`

**Comment by squidfunk** [comment]
Thanks for all your hard work on MkDocs and all the best for your future!

**Pull request merged**
