### PR TITLE
Remove `include_nav` and `include_next_prev`

### LINKED ISSUE #679: Drop `include_nav`, `include_next_prev` from config and context.
We should consider dropping the `include_nav` and `include_next_prev` config.
The only theme that currently references them is the builtin `mkdocs` theme, and this could presumbly instead use...

    {% if nav|length > 1 %}

...and...

    {% if next_page or prev_page %}

For contextual switching, instead of using the current context variables.

### PR DESCRIPTION
**Pull request by tomchristie**
Closes #679.

I still need to eyeball this to verify that the template `nav|length>1` filtering really does behave as expected.

### CODE REVIEW

**Comment by tomchristie** [comment]
Works as expected...

single page:

image

multiple pages:

image

**Comment by tomchristie** [comment]
I leave the decision on this to you @d0ugal. Personally I think we should just go ahead with it and document in release notes that those two bits of config/context have been removed (anyone with a custom theme who's updating *might* need to act on that.)

**Comment by tomchristie** [comment]
Would close these:

* https://github.com/mkdocs/mkdocs-bootstrap/issues/5
* https://github.com/mkdocs/mkdocs-bootswatch/issues/4

**Comment by d0ugal** [comment]
Seems reasonable. Away until Sunday, so won't take a proper look until then.

There is a way in config_options to deprecate options - which means we can show people a specific error rather than one like "this doesn't exist" - it is undocumented and unused because of $reasons. I can show you an example next week.

The purpose of it was for moving non-behavioural config options under extra. I pulled the move from the last release but left the code to do it still.

It might need some tweaking for config options that are being just removed vs moved.

**Comment by d0ugal** [comment]
@tomchristie See #684. I searched a bit on GitHub and see a few people using it so I think it is worth showing something a bit more descriptive.

It's a bit confusing as your dev branch is on the mkdocs repo, the PR is for that.

**Comment by tomchristie** [comment]
> It's a bit confusing as your dev branch is on the mkdocs repo, the PR is for that.

I guess it'd be worth me starting to use `tomchristie/mkdocs` instead, right?

**Comment by d0ugal** [comment]
> I guess it'd be worth me starting to use tomchristie/mkdocs instead, right?

I don't have any strong opinions, so it is up to you. I just prefer to keep dev branches in my fork. I am not even sure GitHub will let you as https://github.com/tomchristie/mkdocs redirects to `mkdocs/mkdocs`

**Comment by d0ugal** [comment]
Two further things.

- `mkdocs.config.config_options.NumPages` (and related tests) can be removed with this change.
- Needs an addition to the release notes.

**Comment by d0ugal** [comment]
I plan to come back to this and update it for the next release, but anyone else interested should feel free to have a go first.

**Comment by waylan** [comment]
I've updated this and went with graceful deprecation in #1026. I'm closing this in favor of #1026.

**Pull request closed without merging**
