### PR TITLE
Pass config file path through SubConfig to Config

### PR DESCRIPTION
**Pull request by couling**
This ensures FilesystemObject fields in Config are correctly evaluated relative to mkdocs.yaml.

See #3264

### CODE REVIEW

**Comment by oprypin** [comment]
Thanks for the PR.

Well, the more important thing here would be adding a test that would've failed before. Also I'll need to think for a bit whether there are any implications for passing `config_file_path` to all subclasses of `Config` or whether it can be considered a breaking change by now

**Comment by couling** [comment]
@oprypin Thanks!  Please confirm that my legacy unit test is actually a legacy unit test, I've not used that style before. Hopefully this will be non-breaking.

**Comment by oprypin** [comment]
Hi sorry, I'm overthinking how to deal with a pull request. Would it be OK for me to just push my edits to this pull request?

**Comment by couling** [comment]
Yeah should be fine. I don't recall if I have a local copy so please don't force push.

**Review by oprypin — APPROVED** [review]

**Pull request merged**
