### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by RussellTaylor83**
Updated documentation, mkdocs help is no longer valid, suggested mkdocs --version instead.

### CODE REVIEW

**Comment by d0ugal** [comment]
Good spot! I think we should go for `mkdocs --help`. It is a bit more useful than `--version` as it helps users discover the other commands.

**Comment by RussellTaylor83** [comment]
I had thought that, but mkdocs --help isn't listed as a command, and it does exactly the same as just mkdocs. Either way is fine, it proves it's run. --version was consisten with testing Python and Pip though :)

**Comment by d0ugal** [comment]
Yeah, okay - that seems reasonable.

**Comment by d0ugal** [comment]
Thanks! 
thumbs

**Pull request merged**
