### PR TITLE
upgrade jquery in mkdocs theme

### PR DESCRIPTION
**Pull request by dfober**
jquery-1.10.2.min triggers security alerts on github. This PR upgrade jquery to version 3.6.0

### CODE REVIEW

**Comment by oprypin** [comment]
Thanks. But does everything keep working? Have you tried clicking around everything and checking for errors?

**Comment by dfober** [comment]
I have 2 sites based on mkdocs theme, there are online (using the upgraded version) at https://guidodoc.grame.fr and https://inscoredoc.grame.fr and I didn't noticed any change.

**Comment by oprypin** [comment]
Hm why is it 3.6.0 and not 3.6.4 let's say :thinking:

**Comment by dfober** [comment]
I've upgraded to the same level than readthedocs. (A bit lazy, the js was available right next door)

**Comment by oprypin** [comment]
OK makes sense then

**Review by oprypin — APPROVED** [review]

**Comment by dfober** [comment]
Great !

**Pull request merged**
