### PR TITLE
Keep the prior behavior of overwriting File.page

### PR DESCRIPTION
**Pull request by oprypin**
unless the page value is a *strict* subclass of Page

* Addresses https://github.com/mkdocs/mkdocs/pull/3367#issuecomment-1710729408

@squidfunk @ultrabug

### CODE REVIEW

**Comment by squidfunk** [comment]
LGTM. So, the regressions that we've seen should be gone, but judging from the code, you decided to issue warnings if a plugin overwrites `Page`. Are we planning to switch to the behavior proposed in #3367 in MkDocs 1.6?

**Review by squidfunk — APPROVED** [review]

**Comment by oprypin** [comment]
You'll be able to move forward with your plugin in 1.5.3 because you're working with strict subclasses and they're supported without warning. For other cases I kept old behavior and added warnings.

**Comment by squidfunk** [comment]
Thanks, yes, I was asking what the plans for 1.6 were, because [the warning](https://github.com/mkdocs/mkdocs/pull/3381/files#diff-de72283007c995e5aa484d7f2e25d4a0c65ac42baeaf46c94db80147fee72beaR211) is not entirely clear to me:

``` py
warnings.warn(
  "A plugin has set File.page to an instance of Page and it got overwritten. "
  "The behavior of this will change in MkDocs 1.6.",
  DeprecationWarning,
)
```

**Comment by oprypin** [comment]
Here's the list of cases:
* Strict subclass: 1.5.3 just accepts it and 1.6.0 still just accepts it
* Page: 1.5.3 ignores/overwrites it with warning, 1.6.0 just accepts it &nbsp; &larr; what you're asking about
* Other type: 1.5.3 ignores/overwrites it with warning, 1.6.0 errors
* None: always ignore/overwrite

**Comment by squidfunk** [comment]
Perfect, thanks!

**Review by ultrabug — APPROVED** [review]
Awesome thanks!

**Pull request merged**
