### PR TITLE
zh_CN: Complete the translation of the mkdocs theme

### PR DESCRIPTION
**Pull request by xingkong0113**
Complete translation both
        mkdocs
        and
        readthedocs
        themes.
        
        Signed-off-by: xingkong0113 <26911141+xingkong0113@users.noreply.github.com>

### CODE REVIEW

**Comment by ultrabug** [comment]
@xingkong0113 thank you for your contribution!

Could you please add your proposed locale to both [mkdocs and readthedocs themes' documentation](https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/choosing-your-theme.md#mkdocs-locale) ?

Cheers

**Comment by xingkong0113** [comment]
> @xingkong0113 thank you for your contribution!
> 
> Could you please add your proposed locale to both [mkdocs and readthedocs themes' documentation](https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/choosing-your-theme.md#mkdocs-locale) ?
> 
> Cheers

hi ultrabug
Which file should I change?
thanks

**Comment by ultrabug** [comment]
@xingkong0113 thanks, please fill the `Last-Translator` field too

**Review by ultrabug — APPROVED** [review]
I intend to merge this in 1 day

**Comment by ultrabug** [comment]
Thanks a lot @xingkong0113 :)

**Comment by oprypin** [comment]
@ultrabug You merged this as "Create a merge commit" but you must always select "Squash and merge".

image

**Comment by ultrabug** [comment]
:ok_hand:

**Pull request merged**
