### PR TITLE
Switch to GitHub Actions from Travis

### PR DESCRIPTION
**Pull request by waylan**
This is a work in progress. 

Still need to add a deploy workflow and remove the Travis config.

Addresses #2032.

### CODE REVIEW

**Comment by waylan** [comment]
@tomchristie I believe you need to enable "Actions" for the entire org. Go to the [mkdocs organization page][1], select the "Settings" tab (which is not available to me), select "Actions" from the sidebar, ensure the "Enable local & third party Actions for this organization" option is checked and click "Save". Note that in another project of mine, the "Enable local & third party Actions for this organization" was already selected, but things didn't work until after I  "saved" it. Once you do that once, it should be good going forward.

Please report back here afterward so I can push another change to trigger a run. Thanks.

[1]: https://github.com/mkdocs

**Comment by tomchristie** [comment]
Done. 👍
Also, we should make you an org admin too.

**Comment by tomchristie** [comment]
Switched you to owner on the org too, not sure why we’d not done that before really.

**Comment by waylan** [comment]
Something is still preventing the actions from running. Not sure what. I don't see any errors in the config file. If anyone else whats to take a look, fell free.

**Comment by facelessuser** [comment]
If you were to create a branch directly on the repo does it work?

**Comment by epicfaace** [comment]
@waylan  Try removing the "tags" section?

Try replacing the top condition with something like

```
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
```

**Comment by facelessuser** [comment]
@epicfaace it's not that because I have it set up the same way with no issues: https://github.com/facelessuser/soupsieve/blob/master/.github/workflows/build.yml.

**Comment by facelessuser** [comment]
@epicfaace, I see you've uploaded a test. You'll see that it doesn't work either. I'm pretty certain that if a branch was created directly on the `mkdocs` repo, not a fork, that it would work. I think once it is running and committed to master, forks could work. That is assuming that actions are correctly enabled on the mkdocs repo, but I do not have permission to check such things 🤷.

**Comment by waylan** [comment]
> I'm pretty certain that if a branch was created directly on the mkdocs repo, not a fork, that it would work. 

Based on my testing, this is not a factor. It works either way assuming there are no other issues.

**Comment by facelessuser** [comment]
You're probably right. When the actions work, they work pretty good, but when they don't it can be cryptic why it fails. That is probably my one complaint.

On a lesser note, sometimes certain combinations you'd expect to work one way, and it seems to not work that way at all. It can be surprising at times.

**Comment by waylan** [comment]
> I'm pretty certain that if a branch was created directly on the mkdocs repo, not a fork, that it would work.

I decided to test this and created a [PR on my own fork][1]. Sure enough, the checks began to run immediately. Still having a weird issue with PYPY3 and Windows though. Once I get that worked out, I'll move it to here. Any help with the issue would be appreciated as it has me stumped.

[1]: https://github.com/waylan/mkdocs/pull/4

**Comment by facelessuser** [comment]
> I decided to test this and created a PR on my own fork. Sure enough, the checks began to run immediately.

It is nice to have that theory confirmed.

> Any help with the issue would be appreciated as it has me stumped.

I'll see if I can squirrel away some time and see if anything stands out to me.

**Comment by waylan** [comment]
Turns out the problem with pypy is a known bug, which has been fixed and will be available in the next release. See tox-dev/tox#1704 for details. In the meantime, I disabled running the Windows/pypy combination of tests. With that, everything it working now.

**Comment by waylan** [comment]
I'm closing this in favor of #2223, which is on a branch of the mkdocs project within the org rather than from an external fork. Of course, the checks ran upon creating the PR.

**Pull request closed without merging**
