### PR TITLE
fix #3599

### LINKED ISSUE #3599: Readthedocs theme doesn't output any link when repo_url is not github or gitlab
Commit 49d02e4 for #3435 doesn't make the template engine actually render the link, probably because of the Jinja expression used.

### PR DESCRIPTION
**Pull request by loulecrivain**
Tested on my env and works, previous Jinja expression was broken (see issue #3599 )

### CODE REVIEW

**Comment by oprypin** [comment]
Hi. So you've confirmed that:

* The problem doesn't happen with your pull request

Could you just triple-check that:

* The problem actually happens when you **revert your commit** but keep everything else.

Because in terms of code, I'm almost fully sure that the change you're proposing makes no difference in terms of hitting this branch.

**Comment by loulecrivain** [comment]
@oprypin tested with latest release this morning, the problem actually happens without the modification (latest mkdocs pypi release, 1st mkdocs install is my version).
```sh
(venv) lou@pluton:~/src/fedimon/fedimon-mkdocs-exporter$ cat mkdocs.yml 
site_name: FediMon Docs
repo_url: https://git.argent.systems/fedi-mon/fedimon-docs/
repo_name: Git repo 
theme:
  name: readthedocs
exclude_docs: |
  /_templates/

(venv) lou@pluton:~/src/fedimon/fedimon-mkdocs-exporter$ grep -Rl 'https://git.argent.systems/fedi-mon/fedimon-docs' site | wc -l
40
(venv) lou@pluton:~/src/fedimon/fedimon-mkdocs-exporter$ pip -q uninstall mkdocs
Proceed (Y/n)? Y 
(venv) lou@pluton:~/src/fedimon/fedimon-mkdocs-exporter$ pip -q install mkdocs
(venv) lou@pluton:~/src/fedimon/fedimon-mkdocs-exporter$ mkdocs -q build 
(venv) lou@pluton:~/src/fedimon/fedimon-mkdocs-exporter$ grep -Rl 'https://git.argent.systems/fedi-mon/fedimon-docs' site | wc -l
0
```

**Comment by oprypin** [comment]
I know that it happens with latest **release** because it's not fixed there yet.
Could you actually do what I'm saying though?

**Comment by loulecrivain** [comment]
@oprypin just did on my side. Well, it appears I've made a patch too hastily :yum: should've checked with latest source beforehand... thx for the doublecheck, will close the issue and the MR. sorry about this !

**Comment by oprypin** [comment]
Thanks 😅
Yeah I really should make a release soon

**Pull request closed without merging**
