### PR TITLE
Add all ancestors to a page

### LINKED ISSUE #693: current_page.ancestors only contains direct ancestor and not the full path of the page
I'm using the mkdocs theme and tried to enhance it with a breadcrumb trail. The page navigation is created automatically by mkdocs (I don't use the pages confguration since I have almost 300 pages).
I copied and adapted the `breadcrumbs.html` file from the readthedocs theme and integrated it in `content.html`:
```
<ol class="breadcrumb">
<li><a href="{{ homepage_url }}">Docs</a></li>
{% if current_page %}
  {% for doc in current_page.ancestors %}
    {% if doc.link %}
      <li><a href="{{ doc.link|e }}">{{ doc.title }}</a></li>
    {% else %}
      <li>{{ doc.title }}</li>
    {% endif %}
  {% endfor %}
{% endif %}
{% if current_page %}<li>{{ current_page.title }}</li>{% endif %}
</ol>
```
My file path (starting from the `docs_dir`)  is:
`beheerteam/diensten/algemeen/ActiveDirectory.md`
The generated breadcrumb trail is:
`Docs/algemeen/ActiveDirectory`

`algemeen` is the only part that originates from the loop `for doc in current_page.ancestors`.

Maybe this is a stupid question or it is just not possible, but I couldn't find i in the documentation and I'm just starting with mkdocs and couldn't understand the source on how this works.

### PR DESCRIPTION
**Pull request by d0ugal**
Fixes #693

### CODE REVIEW

**Comment by rickpeters** [comment]
Wow, great speed at responding to my issue. I'm impressed and forever grateful. Keep up the good work, can't wait to welcome the 0.15.0 milestone :-)

**Comment by d0ugal** [comment]
@rickpeters You got lucky - I am sprinting on things at EuroPython :)

**Comment by rickpeters** [comment]
No matter the reason, I'm still happy! Enjoy yourself! :)

**Comment by rickpeters** [comment]
Great work, I'll look into testing this based on the test instructions for the development master in the docs. Should be able to figure this out and see if my breadcrumbs work as intended.

**Comment by d0ugal** [comment]
Great, thanks! Feedback would be much appreciated.

**Comment by rickpeters** [comment]
Hi, I'm trying to test, however I already get stuck on the installation instructions on the *contributing* page.
If I try and run `pip install https://github.com/mkdocs/mkdocs/archive/master.tar.gz` I get lots of errors.
```
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', gaierror(-2, 'Name or service not known'))': /mkdocs/mkdocs/archive/master.tar.gz
```
I should say that I'm doing this inside a docker container, so that could very well be the reason. However just running `pip install mkdocs` works just fine.
I'm very new to this, so sorry if I ask stupid things. Richt now I'm just dabbling around using python for converting our mediawiki documentation towards mkdocs markdown. I'm very satisfied with the results (thanks).
Other thing I did was upgrade the mkdocs default template to the current bootstrap version and I added some extra styles that are used in the bootstrap documentation itself. Especially the bs-callout with the sidelines. Next step was adding the breadcrumbs and that's what led me to this.
If I can be of any help, just ask and I'll try.

**Comment by rickpeters** [comment]
Hold your horses, my (docker) error. Something to do with activating a VPN (Enterprise rules :-( ) and then going back to normal internet connection. I rebooted the machine and everything works now. Ready for testing, I'll keep you posted.

**Comment by rickpeters** [comment]
Hi Dougal,
just tested it succesfully and it works like a charm! Thanks very much. I attached an image so you can see the breadcrumb trail as proof :-).
breadcrumb

I also attached the menu-dropdon so you can see the navigation.
navigationmenu

Just one question about the full chain of ancestors. I think I would have expected that the *base* directory would also be a ancestor. Meaning that I would have expected the path to be `PLP / Afnemers / Ontwerp / Uitgangspunten / CloudPrincipes`
The `Afnemers` part is missing which is not a real problem since in the menu itself this is marked as the *active* menu.
However I was still wondering if this is a specific design decision on your part?

Regards and thanks very much, I'll keep using the master branch for now until the next release comes out.

Rick

**Comment by rickpeters** [comment]
Did some more testing. It seems that only the 2 first ancestors are added. Meaning that if there are more then 2 levels it still doen't work? I think it should act in some recursive kind of way. As it is I only get the parent and the grandparent, bur nut further up the chain?
Don't know if this would be possible?

**Comment by d0ugal** [comment]
Oh, that's interesting. I thought what I added was recursive. I'll need to try and take another look - I rushed the fix a bit.

**Comment by rickpeters** [comment]
No problem, I'll patiently await an even better solution :-) I have full confidence in it.
And since I've got my test setup right now I'll be able to test it without delay.
To be honest, I'll be going on holiday next tuesday (without my laptop :-) ), so nu rush from my side. Take your time and keep up the good work.

**Pull request merged**
