### PR TITLE
fix MarkdownExtensions type annotation

### PR DESCRIPTION
**Pull request by rmorshea**
based on the validation function any of the following are possible:

- `list[str]`
- `dict[str, Any]`
- `list[dict[str, Any]]`

### CODE REVIEW

**Comment by oprypin** [comment]
This annotation isn't about the input but about what `run_validation` returns. And it does seem to return `List[str]`, so correct.

What is the reason that you ran into this and wanted to change this?

**Comment by rmorshea** [comment]
Hmm, perhaps when I'm

**Comment by rmorshea** [comment]
Looking more closely it seems like those extra configuration options get stored under `mdx_configs`. The docstring says it's for internal use only, is it appropriate to mutate extension options in `on_config` in the way I suggested?

**Comment by oprypin** [comment]
It might be the case that the types for configs are all messed up during `on_config`. I'll need to look later. Could you post your last message as a Discussion - how to set an extension's config

**Comment by rmorshea** [comment]
https://github.com/mkdocs/mkdocs/discussions/3226

**Pull request closed without merging**
