### PR TITLE
Adding search input field labels using aria-label

### LINKED ISSUE #3045: Missing labels for the search boxes in the readthedocs theme (accessibility issue)
We use mkdocs for our company handbook and when running the Wave accessibility evaluation tool we noticed that the search boxes are missing labels. You can see the error here https://wave.webaim.org/report#/https://handbook.civicactions.com/en/latest/search.html?q=leave and screenshot: 

Wave error report

Recommendation is to use `aria-label` to add the missing label. See https://www.w3.org/TR/WCAG20-TECHS/ARIA14.html for examples. I will submit a pull request to add the missing label.

I reported the same error for the Sphinx readthedocs theme: https://github.com/readthedocs/sphinx_rtd_theme/issues/1379

### PR DESCRIPTION
**Pull request by dmundra**
Fixes #3045

### CODE REVIEW

**Comment by ultrabug** [comment]
We actually sync the theme from its [readthedocs upstream](https://github.com/readthedocs/sphinx_rtd_theme) so maybe this should be added there first hand?

**Comment by dmundra** [comment]
Ya I submitted a fix upstream as well https://github.com/readthedocs/sphinx_rtd_theme/pull/1380

**Comment by dmundra** [comment]
FYI, the upstream patch has been merged. Should this wait for a new release of sphinx_rtd_theme?

**Comment by oprypin** [comment]
I will not require waiting, it could just be merged, because I know it will match up with upstream eventually.
On the other hand, the is no release of MkDocs planned soon anyway...

**Review by ultrabug — APPROVED** [review]

**Comment by Sparticuz** [comment]
fyi: i've put a pr in for rtd 1.1.1 (#3058), though @dmundra's patch upstream will probably be on 1.1.2.

**Review by oprypin — APPROVED** [review]

**Pull request merged**
