### PR TITLE
Adds the ability to include yaml files in each other

### PR DESCRIPTION
**Pull request by aeslaughter**

### CODE REVIEW

**Comment by d0ugal** [comment]
This functionality is provided by python-markdown extensions. For example: https://pypi.python.org/pypi/markdown-include

I don't think this belongs in MkDocs itself.

**Comment by waylan** [comment]
No, this allows the YAML config file to "include" sub-YAML files. This has nothing to do with Markdown.

Regardless, it is not clear to me what the use-case would be for this feature. In some projects, there may be multiple configs for development/testing/production, but MkDocs is a pretty simple project and shouldn't need multiple configs. Besides, being a static site generator, there is no distinction between development and production. Therefore, I agree this should be closed, albeit for a different reason than @d0ugal stated.

**Comment by aeslaughter** [comment]
The use case for this is that I have a basic configuration that does not change and will be checked into our project repository (https://github.com/idaholab/moose). However, the pages that that will be displayed will be generated on-the-fly as a part of our continuous integration (i.e., the change will not merge unless the website builds correctly).

mkdocs.yml
```
theme: readthedocs
pages: 
    - Home: index.md
    - Getting Started: getting_started.md
    - Systems: !include Systems.yml # this will be generated with CI
```

**Comment by waylan** [comment]
Similar requests have been made in #641, #357, and #884 (and possibly others - those are the ones I found in a quick search). In each case, the request was denied in favor of a future Plugin API (see #206). I suspect this would fall into the same category.

Additionally, when it was pointed out that YAML already supports defining Python types [here][1], the [reaction][2] was that MkDocs should disable that default behavior of YAML as it is ugly. In this case, you are introducing a similar non-default syntax to YAML. If there is a non-YAML hacking way to do this, that would be the preferred method.

[1]: https://github.com/mkdocs/mkdocs/issues/212#issuecomment-115404162
[2]: https://github.com/mkdocs/mkdocs/issues/212#issuecomment-115573329

**Comment by aeslaughter** [comment]
Thanks for the info, we will probably just use a fork of MkDocs until there is a way to plugin to the MkDocs API.

**Comment by d0ugal** [comment]
Thanks for the clarification @waylan. Luckily my conclusion is the same :smile:

**Pull request closed without merging**
