### PR TITLE
Fetch remote inherited config via http

### PR DESCRIPTION
**Pull request by garryod**
Allows inherited configurations, specified via the `INHERIT` entry in `mkdocs.yml` to be retrieved from a remote server via HTTP(S). See #3552 for rationale

E.g.
```yaml
INHERIT: https://example.com/parent-config.yml
```

Where a scheme cannot be parsed out of the URL the entry is treated as a local file, meaning this change is backwards compatible (except in the instance where a user has a file named `http://something`)

### CODE REVIEW

**Comment by pawamoy** [comment]
Hello, thanks for your contribution. Has this been discussed prior to this PR?

**Comment by garryod** [comment]
Hi Timothée, it hasn't, I wasn't exactly sure if it would be considered a "large" change. Where would be the best place to discuss the change?

**Comment by pawamoy** [comment]
I see, the word "large" in contributing.md might not be the best choice. Your changes here are not large indeed, in terms of lines of code, but they are impactful nonetheless. Please open a new issue where you describe in details *why* you think MkDocs should be able to inherit configuration using HTTP(S) URLs :slightly_smiling_face:

**Comment by garryod** [comment]
> Please open a new issue where you describe in details _why_ you think MkDocs should be able to inherit configuration using HTTP(S) URLs

Done, see #3552

**Pull request closed without merging**
