### PR TITLE
Avoid `background-attachment: fixed` for better performance

### PR DESCRIPTION
**Pull request by yeraydiazdiaz**
Attempt at addressing #1394 

I can't test it myself on a big screen, could @rpkilby or others test if it indeed solves the problem?

### CODE REVIEW

**Comment by rpkilby** [comment]
Thanks @yeraydiazdiaz - that works. 

For whatever reason when I was mucking around earlier, I couldn't get the styles to apply correctly. 

¯\\\_(ツ)_/¯

**Comment by yeraydiazdiaz** [comment]
Glad to hear that 👍

**Comment by rpkilby** [comment]
Also, not sure if it's worth adding a note explaining the change. eg,

```css
/* Replacement for `body { background-attachment: fixed; }`,
   which has noticeable performance issues on large displays. */
```

**Comment by waylan** [comment]
Thank you @rpkilby for the report and suggested comment. And thank you @yeraydiazdiaz for the fix.

**Pull request merged**
