### PR TITLE
Provide german locale file for readthedocs theme

### PR DESCRIPTION
**Pull request by Alzi**
I was missing the translation for my own use and thought, I could contribute it as well. :) Hope I did everything right.

### CODE REVIEW

**Comment by oprypin** [comment]
You translated the "readthedocs" theme. Would you also be interested in translating the adjacent "mkdocs" theme.

**Comment by oprypin** [comment]
Hi @Alzi,
I'm very sorry that I took so long to reply here.
The pull request is fully good and can be merged. Thanks.
However, in the meantime we merged a big update to the "readthedocs" theme, which added many new strings to translate.
https://github.com/mkdocs/mkdocs/pull/2585
If you know how to merge in those changes (`git pull`), you can do it in this pull request and then update the rest of the translations with the same tool you've been using. You can also say that you will do it separately or don't want to do it, then I'll just merge this pull request as is

**Comment by Alzi** [comment]
Hi @oprypin,
thank you for your message and your response-time is totally fine. :) I updated the translation and would like to mention, that I decided to leave certain words in their English form. (Breadcrumb, Mobile, Footer) I believe, these are fairly well known terms, especially in this context. If I should be more strict, please let me know.

**Review by oprypin — APPROVED** [review]
Thank you!

**Comment by ultrabug** [comment]
Thanks and sorry for not stepping in mates

**Pull request merged**
