### PR TITLE
Add chocolatey to list of supported package managers

### PR DESCRIPTION
**Pull request by pascalberger**
I created a [MkDocs Chocolatey Package](https://chocolatey.org/packages/mkdocs). Therefore this PR, to mention Chocolatey as supported package manager.

### CODE REVIEW

**Comment by waylan** [comment]
I'm 'meh' about this (chocolatey is hardly common), but with failing tests I can wait. I realize the flake8 tests have nothing to do with this change (you can ignore them, although I'm concerned how we missed them before), but the [markdownlint][1] test needs to pass. Please rewrap the paragraph you edited (any decent text editor should have a feature which does that for you with a single keyboard shortcut).

[1]: https://travis-ci.org/mkdocs/mkdocs/jobs/175856686#L223

**Comment by pascalberger** [comment]
@waylan I fixed the markdownlint issues

**Comment by waylan** [comment]
@pascalberger, thank you. Unfortunately, GitHub won't let me merge this because we have a failing test that is marked "required". If you merge your branch with upstream, then you'll get the flake8 fix I pushed yesterday and the tests should pass for this. And yes, I realize I could merge this locally, but I'd rather not have to.

**Comment by pascalberger** [comment]
@waylan I've rebased the branch to the current master

**Pull request merged**
