### PR TITLE
Install theme via theme_url [implement #179]

### PR DESCRIPTION
**Pull request by ngzhian**
This is an updated PR from #221.

### CODE REVIEW

**Comment by d0ugal** [comment]
Nice! By the way, don't worry about the appveyor fail - the tests are currently failing on Windows. See #396 where I'm trying to fix that. The travis tests will need fixed tho' and then I can do a review :)

**Comment by ngzhian** [comment]
@d0ugal weird, the 2 test that failed seem to be some 404 error. That's a good chance to discuss with the way the test is written currently is suitable at all.

**Comment by d0ugal** [comment]
@ngzhian The problem is that you put testing data (yeti.zip) into the themes directory. We should only have themes directories in there. I'd move testing data into the tests directory.

**Comment by d0ugal** [comment]
To add further details - the integration test builds all themes, to find all the themes it looks in the theme directory. Until you added a zip file it only contained directories and no files - we could add a check to make sure it is a directory but I'd rather not have test data in there anyway.

**Comment by ngzhian** [comment]
@d0ugal sweet, moved the zip file to `tests/` and tests passed.

**Comment by d0ugal** [comment]
I played around with the code a bit and had a few suggestions. I sent you a pull request here: https://github.com/ngzhian/mkdocs/pull/1 - do you think they all make sense?

**Comment by d0ugal** [comment]
I've rebased this to fix the conflict in #424

**Pull request closed without merging**
