### PR TITLE
Automatically refresh the browser on edits

### LINKED ISSUE #163: Automatically refresh documentation when using `mkdocs serve`
This would make the eediting experience really neat. @ericholscher had an idea for a GUI app that could do this, but this approach might be enough.

One possible approach - inject some JavaScript that either polls or uses web sockets to be notified of an update.

### PR DESCRIPTION
**Pull request by d0ugal**
Use python-livereload to automatically refresh your browser when changes are saved.

Closes #163

### CODE REVIEW

**Comment by d0ugal** [comment]
Dropping watchdog and our hacky webserver for livereload seems like an epic win on it's own, but then we get automatic page refreshing thrown in fro free.

**Comment by d0ugal** [comment]
The auto-reloading isn't as fast and slick as I would like, but generally this is working well. The serve output is totally different. Looking for a way to make it seem more familiar as we lost some information from before.

**Comment by ngzhian** [comment]
wow this is great! the `serve.py` has almost no code right now :+1:

**Comment by d0ugal** [comment]
@ngzhian Yeah, it's really neat :) Have you tried it? The output is quite different than before, but I think it is probably okay.

**Comment by d0ugal** [comment]
@robinandeer if you still use a similar setup, would you be able to help by testing out the latest git master? You helped in the past with an issue regarding auto-reload and docker/vagrant (#178) . I'm concerned this change may have brought that issue back, but I'm not sure how to best test it.

**Comment by robinandeer** [comment]
I've dropped my Docker setup. It quickly became a little too complex running on a Mac. However, I'd be happy to try out a Vagrant environment! Will get back soon.

**Comment by d0ugal** [comment]
@robinandeer Thanks! I'll try and give it a test too - I was being lazy :)

**Comment by d0ugal** [comment]
Unfortunately I had to revert this, I was able to test on Windows early this morning but it seems that python-livereload doesn't work well on Windows. I'll investigate later and then hopefully figure out a way to make this work.

**Comment by d0ugal** [comment]
New attempt will be at #433

**Pull request merged**
