### PR TITLE
Add mkdocs command troubleshooting help on Windows

### PR DESCRIPTION
**Pull request by advancedrei**
Searched everywhere to figure out how to fix this, finally found it here: https://www.sitepoint.com/building-product-documentation-mkdocs/. Adding to the docs to save the next poor soul from wasting 2 hours. :/

### CODE REVIEW

**Comment by waylan** [comment]
You have a few [Markdown Lint errors][1] that will need to be corrected before this is accepted, if it is. To me this addition seems unnecessary, but then I've been using Python for years and know this without even thinking about it (I'd be surprised if it worked without doing that). I realize that may not be the case for new users. I just wonder if this could be worked into the Windows install instructions in a more subtle way rather than creating a new sub-section in the docs.

[1]: https://travis-ci.org/mkdocs/mkdocs/jobs/135322113#L194

**Comment by advancedrei** [comment]
@waylan I have been a .NET developer for 15 years, but was new to Python until today. The Chocolatey manager, which this project recommends, does not appear to update the PATH variable when installing Python. So I wanted to make sure users get the info they need.

The reason I created a separate section is because the docs just assume your installation will be successful. They do not provide any assistance if it fails, which based on a review of the Issues and Google Groups, can happen often. This was my attempt to start building out a troubleshooting section of common issues for all platforms, so new users can get productive more quickly.

**Comment by waylan** [comment]
> does not appear to update the PATH variable when installing Python.

That has been normal behavior for as long as I can remember, regardless of installation method. IIRC, some newer Python versions do update the PATH variable when installed in certain ways, but that is only for the Python runtime (`python.exe`), not the Python "bin" dir (annoyingly named "Scripts" on Windows). The docs should be written with that assumption in mind. Incorporating a comment into the basic installation instructions rather than a separate "troubleshooting" section would accomplish that.

As an aside, I always assumed Chocolatey was being recommended because it handled things like updating the PATH variable (I've never used Chocolatey personally). Perhaps the problem is that none of the core developers use Windows as their primary/development system.

**Comment by advancedrei** [comment]
Yes, that seems like a pretty big problem. Another one is that the documentation assumes a lot about the skill level and familiarity of the system. Now that .NET is OSS and leveraging projects like this, that's probably not a good thing.

I really don't care what you guys do, I doubt I'll have much else to contribute to the project (at least in the way of code). The right thing to do is to accept the PR so I get contribution credit, and then modify the text as you choose. However, I will point out that your docs assume success and not failure, and the Google Group and Issues section have several different ways installation can fail. To save you support headaches (and keep your users from wasting time) you should probably document those things. Then again, you guys develop with Python, so maybe you like headaches 😀 🙊 😶 😉

**Comment by waylan** [comment]
@d0ugal this is your call.

**Comment by d0ugal** [comment]
> Perhaps the problem is that none of the core developers use Windows as their primary/development system.

Indeed, this is the issue. I don't know what is best to recommend here.

**Comment by d0ugal** [comment]
> Yes, that seems like a pretty big problem. Another one is that the documentation assumes a lot about the skill level and familiarity of the system. Now that .NET is OSS and leveraging projects like this, that's probably not a good thing.

@advancedrei Which projects are using MkDocs?

**Comment by d0ugal** [comment]
> I really don't care what you guys do, I doubt I'll have much else to contribute to the project (at least in the way of code). The right thing to do is to accept the PR so I get contribution credit, and then modify the text as you choose. However, I will point out that your docs assume success and not failure, and the Google Group and Issues section have several different ways installation can fail. To save you support headaches (and keep your users from wasting time) you should probably document those things. Then again, you guys develop with Python, so maybe you like headaches 😀 🙊 😶 😉 

The tone here isn't helpful, we are all volunteers and trying to help make things better. :sparkles: :heart:

**Comment by d0ugal** [comment]
I don't recall doing any  PATH changes when I installed with Chocolately and I am fairly sure I copied everything down that I done. However, this was probably over a year ago and in a windows VM that I don't have now. I'm not sure if anything has changed since then.

Windows support is a "best effort" because we don't have any volunteers on the MkDocs team that are able and willing to help out. Therefore I am going to close this as it stands. I would be very happy for somebody to drive this forward and improve the docs. I had considered the different install options lately #932, perhaps as part of that work we should improve it for Windows users.

**Comment by advancedrei** [comment]
@d0ugal ASP.NET WebAPI and RESTier are likely to start using it at my recommendation... though I'm now likely to see if the Sphinx experience is more user-friendly.

**Comment by d0ugal** [comment]
Okay, I think the issues you had are all Python-on-Windows related so Sphinx is likely to be similar (but requires more understanding of Python IMO). However, It may be better documented as a far more mature project. Anyway, good luck and do report any specific MkDocs issues if you run into them!

**Pull request closed without merging**
