### PR TITLE
Update readthedocs theme with upstream

### LINKED ISSUE #588: Update Read The Docs theme with upstream
The Upstream RTD theme has added some nice features for collapsing the navigation. You can see an example in [pip Sphinx documentation](http://pip.readthedocs.org). We have some users that could benifit from this, like [GlusterFS](http://gluster.readthedocs.org/en/latest/), as they have _many_ pages.

As a side, I happen to think that it is a negative update for smaller projects so I could be tempted to make this optional. Perhaps with an extra: config value like "extra: collapsable_nav: True" which would be specific to this theme? It could either remove the feature totally or expand by default.

### PR DESCRIPTION
**Pull request by waylan**
This updates the `readthedocs` theme to more closely match the [upstream][1] Sphinx theme (at version 0.4.1). This should resolve #588 and #1374. 

The following theme config settings were added:

* __`include_homepage_in_sidebar`__: Lists the homepage in the sidebar menu. As
  MkDocs requires that the homepage be listed in the `nav` configuration
  option, this setting allows the homepage to be included or excluded from
  the sidebar. Note that the site name/logo always links to the homepage.
  Default: `True`.

* __`prev_next_buttons_location`__: One of `bottom`, `top`, `both` , or `none`.
  Displays the “Next” and “Previous” buttons accordingly. Default: `bottom`.

* __`navigation_depth`__: The maximum depth of the navigation tree in the
  sidebar. Default: `4`.

* __`titles_only`__: If True, removes headers within a page from the sidebar.
  Default: `False`.

[1]: https://github.com/rtfd/sphinx_rtd_theme/

### CODE REVIEW

**Comment by Blendify** [comment]
There is no need to feel sorry, I am glad to help. I will take a look.

**Comment by Blendify** [comment]
Some toc options were not included these include:

- `includehidden = True`
- `collapse_navigation = True`
- `sticky_navigation = True`

Is there a reason these are not supported?

**Comment by waylan** [comment]
> Some toc options were not included these include:
>
> * `includehidden = True`

MkDocs' concept of hidden pages is very different from Sphinx and therefore this option makes no sense. As I understand it, Sphinx page objects include a `hidden` attribute. MkDocs page object have no such attribute. A hidden page is simply not included in the `nav` at all. Therefore, there is no way to include such pages.

Or am I misunderstanding the purpose of this setting?

> * `collapse_navigation = True`
> * `sticky_navigation = True`

I haven't worked on these. Basically, I need to determine what is different about the HTML with these options enable/disabled and add the same logic to our template. Personally they are not high priority items so I haven't got to them yet. And the assumption is they could always be added at any time.

**Comment by waylan** [comment]
`stick_navigation` has been added.

I'm struggling to see the difference between `collapse_navigation` and `titles_only`. The documentation seems clearly different, but in practice both setting simply exclude TOC items from the nav. As I already implemented that feature in `titles_only`, what value is there is also adding `collapse_navigation` ?

As an aside, the [documentation][2] for `collapse_navigation`  states: 

> * `collapse_navigation` Bool. With this enabled, you will lose the `[+]` drop downs next to each section in the sidebar.

But that is not strictly true. You still get `[+]` drop downs, just not as many levels of them (tested with the docs in [rtfd/sphinx_rtd_theme][1]). I find that very misleading and its not something I'm inclined to replicate... unless someone can explain to me the value of the setting and/or what it is supposed to be doing.

[1]: https://github.com/rtfd/sphinx_rtd_theme/
[2]: https://sphinx-rtd-theme.readthedocs.io/en/latest/configuring.html#toc-options

**Comment by waylan** [comment]
@Blendify thank you. Those docs are must more clear. I now have the following implemented:

> * __`include_homepage_in_sidebar`__: Lists the homepage in the sidebar menu. As
>   MkDocs requires that the homepage be listed in the `nav` configuration
>   option, this setting allows the homepage to be included or excluded from
>   the sidebar. Note that the site name/logo always links to the homepage.
>   Default: `True`.
> 
> * __`prev_next_buttons_location`__: One of `bottom`, `top`, `both` , or `none`.
>   Displays the “Next” and “Previous” buttons accordingly. Default: `bottom`.
> 
> * __`navigation_depth`__: The maximum depth of the navigation tree in the
>   sidebar. Default: `4`.
> 
> * __`collapse_navigation`__: Only include the page section headers in the
>   sidebar for the current page. Default: `True`.
> 
> * __`titles_only`__: Only include page titles in the sidebar, excluding all
>   section headers for all pages. Default: `False`.
> 
> * __`sticky_navigation`__: If True, causes the sidebar to scroll with the main
>   page content as you scroll the page. Default: `True`.

**Comment by Blendify** [comment]
I will take another look again, but from my first look over, it looked pretty good.

**Pull request merged**
