### PR TITLE
Add a linkchecker test for each theme.

### PR DESCRIPTION
**Pull request by waylan**
Addresses #899. Not sure if this will work. Will have to wait and see what Travis reports.

### CODE REVIEW

**Comment by d0ugal** [comment]
Interesting, codecov has started adding comments. I don't think we want that added noise? I'll take a look at turning them off later.

**Comment by waylan** [comment]
> Interesting, codecov has started adding comments. I don't think we want that added noise? I'll take a look at turning them off later.

I wondered about that. Thought maybe you changed something. Guess not.

**Comment by waylan** [comment]
Hmm, looks like the commands are not actually running.

**Comment by d0ugal** [comment]
I shuffled things around a little bit in #913, it is now simpler but checks all the builds from the integration tests (so all themes with the mkdocs docs plus a few extra docs sites that test specific things like unicode). It seems to be working now, let me know what you think of this approach.

**Comment by waylan** [comment]
Closing this in favor of #913.

**Pull request closed without merging**
