### PR TITLE
Use web worker to build Lunr index

### PR DESCRIPTION
**Pull request by yeraydiazdiaz**
Addresses #1218, #859 and #1127 

Reading the discussion on #859 I decided to give the Web Workers API a try and got a working solution using them. In the process I managed to remove require.js and mustache from the dependencies which seemed overkill for our use case.

I'm not completely replacing the previous code since it's possible the user's browser [might not the Web Workers API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API#Browser_compatibility). Based on our target browser versions we can discuss if we  load or remove the previous version.

I also realised it'd be quite simple to upgrade to the current version Lunr and maybe include [additional language support](https://lunrjs.com/guides/language_support.html) but would require some changes to the configuration, we can discuss it outside the context of this PR.

### CODE REVIEW

**Comment by waylan** [comment]
Awesome. I am going to hold off merging this though. This has been part of a [larger refactor][1] of search and I'd like to get everything worked out before committing to how any one part is implemented. For example, I didn't merge #1061 because I wanted it to work with the webworker stuff (it's also out-of-date but that's another matter).

My intention is to build a **new** search plugin and leave the existing "legacy search" plugin as-is. The two can then reside side-by-side.

[1]: https://github.com/mkdocs/mkdocs/projects/1

**Comment by yeraydiazdiaz** [comment]
That's fine, I was trying to see if the approach would work and how much of the current search funcionality we actually need, turns out it's not a lot.

How would you like to proceed? Feels these changes should be part of #1061 which in turn is part of the larger refactor, but its PR is against master, so I'm a little confused. Is there a branch for this refactor that I'm missing?

**Comment by waylan** [comment]
#1061 was against master before search was broken out into a plugin and was also an experiment to see if the approach would work (it does, although I would do some things a little differently). Today it only exists as a point of reference. I would be more inclined to start working off of this and reimplement #1061 on top of this. In fact, I'm reopening this so it doesn't get lost and forgotten about.

**Comment by yeraydiazdiaz** [comment]
Sounds good, let me know if you'd like some help with it 👍

**Comment by waylan** [comment]
I took this and re-implemented it as a new plugin in the [waylan:new-search][1] branch (see https://github.com/mkdocs/mkdocs/compare/master...waylan:new-search for comparison). I left bea4fcf20 as a separate commit to show how I implemented the non-worker fallback ('ll probably squash it later).

I should note that all of the URLs need to be relative as the root of the site may not be hosted at the server root (ex: `username.github.io/projectname/`). This turned out to be the trickiest thing to work around (when loading the index from the worker the JSON files URL needs to be relative to the worker, but when loading from the main thread, the JSON file's URL needs to be relative to the page). If course, once I had a solution, it was an easy fix, but it may be non-obvious from the code why I did that. 

The entire thing is a work in progress. I've updated the [project][2] to reflect what has been resolved and what is outstanding.  Any feedback and/or improvements are welcome.

[1]: https://github.com/waylan/mkdocs/tree/new-search
[2]: https://github.com/mkdocs/mkdocs/projects/1

**Pull request closed without merging**
