### PR TITLE
Added base_url to config so that improper relative path to static files can be fixed in sub directories of mkdocs theme

### PR DESCRIPTION
**Pull request by akhilputhiry**
I was trying to fix https://github.com/tomchristie/django-rest-framework/issues/4758 which occurs due to relative path of static files.

### CODE REVIEW

**Comment by akhilputhiry** [comment]
@waylan Your thoughts please

**Comment by waylan** [comment]
Two things:

I was of the impression this was fixed in f5b5446b which is included in version 0.16. If not, could you provide a minimum example that still fails?

And finally, your proposed fix does not actually "fix" the problem. If we are generating incorrect URLs, then we should actually fix that. You can find a detailed analysis starting with [this comment][1] (and the few after it).   There should be no need to add a new config option. Everything you would need is already available from the existing options.

[1]: https://github.com/mkdocs/mkdocs/issues/77#issuecomment-242777289

**Comment by akhilputhiry** [comment]
@waylan thanks. let me see.

**Comment by akhilputhiry** [comment]
Things are working fine with latest release. closing this PR.

Thanks @waylan

**Pull request closed without merging**
