### PR TITLE
New command 'add' to create new page from a page template.

### PR DESCRIPTION
**Pull request by MarcProux**
I create this PR to push the right branch. Old PR is https://github.com/mkdocs/mkdocs/pull/1252

### CODE REVIEW

**Comment by waylan** [comment]
Thanks @Daethe. I'll review this when I have some time (it may be a while).

**Comment by Daethe** [comment]
I will continue to improve the command to be able to use variables within the templates that will have to be configured either in a file '_config.yml' or in a header.

So I will create a new branch to handle these improvements and make a new pull request if it is closed.

**Comment by Daethe** [comment]
Issue when running check in 'mkdocs/tests/gh_deploy_tests.py' function 'test_deploy_error'

**Comment by oprypin** [comment]
So this PR is definitely stale (sorry about that). I am also inclined to reject this as a feature request altogether, because the functionality doesn't benefit from being tied to MkDocs: people can easily invent their own external approach that suits them best.
Further discussions on the merits of such a feature can still be brought up if there's more to add.

**Pull request closed without merging**
