### PR TITLE
Remove ghp-import dependency and update gh-deploy

### PR DESCRIPTION
**Pull request by d0ugal**
This works well, but has brought in a ton of untested code. I'll try and do something about that before merging.

### CODE REVIEW

**Comment by Collizo4sky** [comment]
Am here to help you test :+1:

**Comment by d0ugal** [comment]
Thanks! If you want to try it out you can follow this: http://www.mkdocs.org/about/contributing/#testing-the-development-version

**Comment by Collizo4sky** [comment]
Oooopsss. my python skills is nothing close to good hence unit testing Mkdocs is out of the equation.

I could help in manual testing - installing the master branch and testing that everything work as expected.

**Comment by d0ugal** [comment]
The link I sent is about installing the master branch, specifically, the command is:

    pip install https://github.com/mkdocs/mkdocs/archive/master.tar.gz

**Pull request merged**
