### PR TITLE
Release notes for 1.5.0

### PR DESCRIPTION
**Pull request by oprypin**
Preview: https://github.com/mkdocs/mkdocs/blob/relnotes/docs/about/release-notes.md#version-150-2023-07-19

### CODE REVIEW

**Review by pawamoy — APPROVED** [review]

**Comment by pawamoy** [comment]
This is exciting 😁

**Comment by oprypin** [comment]
The release is still delayed, to give some time to downstream:
* https://github.com/byrnereese/mkdocs-minify-plugin/pull/30
* (technically upstream) https://github.com/Python-Markdown/markdown/issues/1360#issuecomment-1644406891

**Review by drunkwcodes — APPROVED** [review]
Good to see `mkdocs get-deps` happening.

I can refine my devguide now.

**Comment by Guts** [comment]
Wow, really exciting changes! :clap: to every contributor!

**Pull request merged**
