### PR TITLE
Added command 'add'

### PR DESCRIPTION
**Pull request by Daethe**
This command allow user to create new file for documentatin following created template.

### CODE REVIEW

**Comment by waylan** [comment]
Interesting. I'm not sure if we ant this but thanks for the submission. I'll do a full review when I have some time. However, this would be included in the 1.0 release at the earliest (if at all), so this should be against the 1.0.dev branch. Could you adjust the PR to reflect that? Obviously, the failing tests would need to be resolved as well.

**Comment by Daethe** [comment]
I change the PR for 1.0.dev branch and I will try to resolve failing tests as soon as possible. When I fully understand it :)

**Comment by Daethe** [comment]
Why check is not running again ?

**Comment by Daethe** [comment]
@waylan Could you help me please ?

Do I need to open new PR with reference to this one ? Because 2 commit [38a0579](https://github.com/mkdocs/mkdocs/pull/1252/commits/38a0579b34399407d6bceda5661cac0870d1efdc) and [46a382d](https://github.com/mkdocs/mkdocs/pull/1252/commits/46a382d82944b8951038481d2afe6bee19bf156f) is into this one and not directly into 1.0dev branch

**Comment by Daethe** [comment]
I create new pull request with reference to this one for correcting branch. I close this one

**Pull request closed without merging**
