### PR TITLE
Fix shortcuts to go to previous or next page

### LINKED ISSUE #3728: Default theme: N and P keys no longer work
Using mkdocs 1.6.0, the default theme is much better than the one in 1.5.x. It has dark mode, awesome!

If you press ? it displays a few keyboard shortcuts.

But if you press the N key to go to the next page, or the P key to go to the previous page, nothing happens, and you get this error in the console:

Uncaught DOMException: Document.querySelector: '.navbar a[rel="next"]:first' is not a valid selector
    <anonymous> http://127.0.0.1:8000/js/base.js:60

### PR DESCRIPTION
**Pull request by squidfunk**
Fixes #3728.

### CODE REVIEW

**Comment by squidfunk** [comment]
Not sure why the build fails. If it's related to my changes, let me know.

**Review by pawamoy — APPROVED** [review]
> If it's related to my changes, let me know.

Doesn't look like it.

---

Thanks!

**Comment by tomchristie** [comment]
> Doesn't look like it.

Eh... yeah resolved now.

Is it worth us bringing this up to date with master just to make sure we're keeping the builds clean?

**Comment by squidfunk** [comment]
> Is it worth us bringing this up to date with master just to make sure we're keeping the builds clean?

I'm not sure I understand. What do you mean by clean? This PR is safe to merge regardless of #3730 (if that was your question), as both PRs fix unrelated things, and do not affect each other in any way.

**Comment by pawamoy** [comment]
I think @tomchristie meant to merge master / rebase on master to get the CI fix in this PR.

**Comment by squidfunk** [comment]
This PR was accidentally deleted. Please see #3787.

**Pull request closed without merging**
