### PR TITLE
Fix Python 3.7 and PEP 479 incompatibility

### PR DESCRIPTION
**Pull request by moigagoo**
With [PEP 479](https://www.python.org/dev/peps/pep-0479/) implemented in Python 3.7, raised `StopIteration` is now translated into `RuntimeError`, which breaks `mkdocs build` command.

The recommended way to exit generators is to use `return` instead of raising `StopIteartion`: https://www.python.org/dev/peps/pep-0479/#id39

### CODE REVIEW

**Comment by waylan** [comment]
Thanks for your contribution. However, this is being closed in favor of #1504 which completely replaces the offending code with a new implementation that does not exhibit the problem.

**Comment by waylan** [comment]
Including a mailing list report, we have received 5 separate reports in 8 days. I guess we should probably apply this fix and do a bugfix release. However, this PR needs to be against the 0.17 branch for that and it's currently against master.

**Comment by moigagoo** [comment]
> However, this PR needs to be against the 0.17 branch for that and it's currently against master.

**Comment by moigagoo** [comment]
@waylan 

> However, this PR needs to be against the 0.17 branch for that and it's currently against master.

Fixed.

**Comment by moigagoo** [comment]
@waylan Oh, I just noticed that you had changed the base yourself back and forth, sorry :-(

**Comment by waylan** [comment]
Notice that by switching the branch we get all of the commits on master up to and including the relevant commit. However, we only want the one relevant commit. Therefore, I cloned your repo locally, cherry-picked your commit and pushed it to #1536. No need for you to do do anything else at this point.

**Comment by waylan** [comment]
Fixed in #1536.

**Comment by waylan** [comment]
Version 0.17.5 is now available with this fix.

**Pull request closed without merging**
