### PR TITLE
Move some documentation into code, add misc API docs page

### PR DESCRIPTION
**Pull request by oprypin**

### CODE REVIEW

**Review by ultrabug — APPROVED** [review]
I like it, thanks

**Comment by pawamoy** [comment]
Can't wait to see the live docs 🙂

**Comment by oprypin** [comment]
@pawamoy Well...

I won't publish the docs for some time still, so anyway you'd have to see `mkdocs serve` for yourself for now.

And actually... at the moment it's a slight downgrade in terms of looks. (though mostly unchanged). I'd probably want a few features out of mkdocstrings to make it actually better. You'll hear from me soon. Or feel free to let me know when you want to discuss :D

But thanks to both for the enthusiasm 😊

**Comment by oprypin** [comment]
Ah, may as well publish it here, though:

https://oprypin.github.io/mkdocs/dev-guide/themes/#page
Before: https://www.mkdocs.org/dev-guide/themes/#page

And the new page:
https://oprypin.github.io/mkdocs/dev-guide/api/

**Pull request merged**
